### ISSUE TITLE
Infinite loading loop after the initial loading sequence

### ISSUE THREAD

**Issue by Pygzig** [Gameslinx/Tessellation#10]
With the stock textures installed, my game will not boot to the main menu. It gets stuck on the black screen with the loading ring thingy.

I can load into the game just fine with just the parallax plugin and no texture pack just fine, though.

https://drive.google.com/file/d/1vbkm_vVoMJOvx2vvjL6hQlije1BJcnCf/view?usp=sharing

**Comment by Gameslinx** [comment]
This isn't Parallax doing that. You've got a lot of other mods, and you're getting exceptions from the core KSP files. I suggest a reinstall of your game
