### ISSUE TITLE
Both Parallax Stock Textures and Scatter Texture Files Download Error: Reads Failed-Needs Authorization More Than Halfway Through

### ISSUE THREAD

**Issue by crystallinesheen** [Gameslinx/Tessellation#100]
I can't seem to download these files without getting this error message. They wouldn't work on CKAN so I tried to manually download them to install to the KSP game data folder and it messed up again. Both times the files downloaded more than halfway before this happened. I've tried Googling the issue and can't find any answer, hope you can help.

**Comment by Gameslinx** [comment]
Try downloading again after registering an account and logging in with Github

**Comment by crystallinesheen** [comment]
I tried that, didn't work. I did get it to download sucessfully though. I
used Microsoft Edge browser instead of Brave, also I switched my internet
from mobile hotspot to house internet. I don't know which of the two did
it, but both downloaded sucessfully. I couldn't get it to download through
CKAN either, all other files worked fine. It's a mystery as these things
usually are. Anyways, thanks for your help!
