### ISSUE TITLE
Nothing showing up.

### ISSUE THREAD

**Issue by V-LTS** [Gameslinx/Tessellation#101]
Fiddled with it for about an hour by now, nothing is showing up, vanilla KSP textures are there but not Parallax. I've reinstalled multiple times, including switching versions of Parallax and reinstalling Kopernicus. It doesn't crash or anything and I've installed everything according to instructions, any help? Some of the mod works fine, such as ctrl+P it'll make the UI show up.

![Reference](https://user-images.githubusercontent.com/113800549/190874306-588779c8-5fd0-468e-a43d-f89021f655f0.PNG)

**Comment by Gameslinx** [comment]
You've installed an old version of Kopernicus, or not installed Kopernicus properly.
Download and install this version: https://github.com/Kopernicus/Kopernicus/releases/download/release-139/Kopernicus-1.12.1-139.zip
You need to move **all** files into GameData. This includes 000_Harmony and ModuleManager

**Comment by V-LTS** [comment]
Works great now! Thanks!
