### ISSUE TITLE
Game Loads to Black Screen and Cursor

### ISSUE THREAD

**Issue by jpart3** [Gameslinx/Tessellation#109]
I downloaded Kopernicus (latest version), EVE, and Scatterer via CKAN.  All appear to be the latest version.  I then downloaded Parallax manually.  Everything appears to be in the GameData folder.  When I launch the game (whether through the Desktop shortcut or via CKAN), I get the same issue:  the screen is black except for the KSP cursor, which functions normally.  I've found other issues online that suggest this may be a Kopernicus problem but cannot find where the hiccup might be.

**Comment by Gameslinx** [comment]
Reinstall Kopernicus and/or KSP. There's a chance that you are using an old release, or missing part of it
