### ISSUE TITLE
Lights on parts breaks scatter lighting

### ISSUE THREAD

**Issue by XeonSquared** [Gameslinx/Tessellation#111]
Hi! I'm using Parallax 2.0.4 on Linux, and I've noticed that if there's any light in the scene, the rocks on the Mun turn black. This issue - or at least, I think it was the same issue - was also referenced in the forum thread [here](https://forum.kerbalspaceprogram.com/index.php?/topic/209714-112x-parallax-pbr-terrain-and-surface-objects-202/&do=findComment&comment=4174366) by Geonovast, but I didn't find any further reference to it.

As I'm using OpenGL, I have shadows disabled in ParallaxGlobal.cfg, but otherwise it is fully defaults. The game settings are default other than Terrain Shader Quality and Terrain Quality. I did try turning off tesselateLighting but it didn't seem to make any difference either way.

Here [output.webm](https://user-images.githubusercontent.com/3684161/194054270-ccae12de-f6f7-4c48-b70d-b5e851f7b3b5.webm) is a video example of the problem, with only Parallax installed on a fresh copy of KSP. The lights on the front of the rover are set to blink once a second. As you can see, the rocks on the right part of the screen turn black when there's lighting in their general area, but distant rocks and the rocks on the left (far away from the light cone?) are as normal as they get without shadows.

Here is my KSP.log: [KSP.log](https://github.com/Gameslinx/Tessellation/files/9715414/KSP.log)

My system is as follows:

```
System:
  Host: nagato.sks.local Kernel: 5.19.11-269-tkg-bmq arch: x86_64 bits: 64
    Desktop: awesome v: 4.3 Distro: Arch Linux
Machine:
  Type: Desktop Mobo: ASUSTeK model: Z170-P D3 v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 2604
    date: 02/22/2018
CPU:
  Info: quad core Intel Core i7-6700K [MT MCP] speed (MHz): avg: 2087
    min/max: 800/4200
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.4 with: Xwayland v: 22.1.3 driver: X:
    loaded: amdgpu unloaded: modesetting,vesa gpu: amdgpu resolution:
    1: 1050x1680~60Hz 2: 1920x1200~60Hz 3: 1080x1920~60Hz
  OpenGL: renderer: AMD Radeon RX 580 Series (polaris10 LLVM 14.0.6 DRM
    3.47 5.19.11-269-tkg-bmq) v: 4.6 Mesa 22.1.7
```

Here are some more picture examples, from my modded game:

![2022-10-04T18:17:55-1920x1200](https://user-images.githubusercontent.com/3684161/194054806-c1428c2b-8587-4bf0-ba7a-89ed407d2085.jpg)
![2022-10-04T18:18:02-1920x1200](https://user-images.githubusercontent.com/3684161/194054866-59c0ed77-2b9a-43b3-b65b-8ca8fa63fed6.jpg)
![2022-10-05T21:50:13-1920x1200](https://user-images.githubusercontent.com/3684161/194054975-d2e98c07-c044-4dac-9e3c-e499e5c082a0.jpg)
![screenshot_2022-09-29T13:23:08](https://user-images.githubusercontent.com/3684161/194055035-2a587cc6-ba8d-43fb-ab42-bee80315bdb5.jpg)
![screenshot_2022-09-29T13:23:09](https://user-images.githubusercontent.com/3684161/194055049-d247f6d0-073c-42cb-bdf6-61e73b70860f.jpg)

Thank you for your time and your work supporting OpenGL users, even though we don't make up a very big percentage of the userbase :)

**Comment by Gameslinx** [comment]
Please increase pixel light count and let me know the effects

**Comment by XeonSquared** [comment]
Alright, I turned them all the way up to 64 (from 8), but it doesn't seem to have had any effect, unfortunately.

![2022-10-08T11:12:27-1282x743](https://user-images.githubusercontent.com/3684161/194677671-0ebd54f7-7514-4416-8e7f-24b7ac97232d.png)
![2022-10-08T11:14:14-1282x743](https://user-images.githubusercontent.com/3684161/194677842-57987014-d8b5-4b02-b69a-531ae22a2fb5.jpg)
![2022-10-08T11:14:19-1282x743](https://user-images.githubusercontent.com/3684161/194677852-261809eb-f20e-4a3b-b71e-255bf2cbb8a4.jpg)

**Comment by Gameslinx** [comment]
This seems like an OpenGL bug. I will investigate
