### ISSUE TITLE
Too Many Trees

### ISSUE THREAD

**Issue by Missile-maker** [Gameslinx/Tessellation#129]
I am using Parallax 2.0.6 and when I spawn in a plane or some sort of craft of any type it puts WAY to many trees at the KSC and I can't fix it
[KSP.log](https://github.com/Gameslinx/Tessellation/files/10798155/KSP.log)
Log

**Comment by Missile-maker** [comment]
![20230212133128_1](https://user-images.githubusercontent.com/109987472/220470011-77b51d24-c402-4f37-b8ac-5bf9c50301ef.jpg)
![20230211093418_1](https://user-images.githubusercontent.com/109987472/220470014-eb1b155f-6151-4d65-9697-adcd17624c94.jpg)
Images

**Comment by Spacernova1** [comment]
i have the same problem

**Comment by Missile-maker** [comment]
> i have the same problem

I figured out the fix so when you set your graphics settings in the main menu, don't set it to the max one, set it to High, the second last one.
