### ISSUE TITLE
Parallax plugin is enforcing V-Sync settings during loading prior to Main Menu

### ISSUE THREAD

**Issue by Poodmund** [Gameslinx/Tessellation#13]
A while back, KSP realised it should disable any V-Sync settings during the game load because all part loads are done per frame so the speed at which the game loads is dependent on frame rate. KSP then enables the V-Sync settings once the game goes into the Main Menu scene.

It seems that Parallax is overriding this and enforcing any V-Sync settings in the Settings.cfg prior to the game loading. 

This can be verified by going into the Main Menu -> Graphics settings and forcing the following:
- V-Sync: Every V-Blank
- Frame Limit: 60fps

Ensure that you're running a FPS counter on the screen i.e. GeForce Experience HUD, and open up Vanilla KSP + Kopernicus Bleeding Edge and Module Flight Integrator with these settings, above, applied. You'll see that the FPS counter goes to like 500-600 (dependent on PC specs) and loads very fast.

Subsequently, install Parallax and Parallax Stock Textures into this build and load KSP, you'll see the FPS counter lock out at a max of 60fps and takes longer to load.

This has a very considerable effect on load times for large, modded installs that run thousands of parts/patches as the frame rate lock can slow down the database construction by, like, a factor of 10.

KSP 1.10.1 + Kop_BE + MFI without Parallax: [KSP.log](https://github.com/Gameslinx/Tessellation/files/5579472/KSP.log) - Total loading Time = 47.994s

KSP 1.10.1 + Kop_BE + MFI + Parallax: [KSP.log](https://github.com/Gameslinx/Tessellation/files/5579480/KSP.log) - Total loading Time = 97.525s

---

KSP 1.10.1 Modded Install with roughly 19,000 patches without Parallax: [KSP.log](https://github.com/Gameslinx/Tessellation/files/5579495/KSP.log) - Total loading Time = 172.975s

KSP 1.10.1 Modded Install with roughly 19,000 patches with Parallax: [KSP.log](https://github.com/Gameslinx/Tessellation/files/5579542/KSP.log) - Total loading Time = 376.637s

**Comment by Li0n-0** [comment]
I can confirm this happening

KSP 1.10.1 + Kop_BE + MFI : 65.375s
KSP 1.10.1 + Kop_BE + MFI + Parallax : 81.523s
KSP 1.10.1 + Kop_BE + MFI + Parallax + StockTexture : 84.014s

(MM cache deleted prior each test)

The frame limiter in KSP don't seem to work very well, no matter what settings I set it lock the framerate at 144Hz, the maximum my monitor can achieve.
I guess this is why my loading is quicker, with Parallax, than @Poodmund 's.

**Comment by Gameslinx** [comment]
This issue has been fixed and will be included in update 1.2.0. Thanks for the reports!
