### ISSUE TITLE
(Linux) Some times textures are set to 4k by default (more testing needed.)

### ISSUE THREAD

**Issue by Gertinin** [Gameslinx/Tessellation#14]
So I was testing out stability with Parallax on Linux and every time the game crashes I check the ksp.log to see what it was. Most of the time Its something that I can't tell what the issue is but, This time the textures for Minmus were set to 4k and, (only time the log has said this so it may be really common), and I can't find any thing to change that in any .cfg file. There 1 thing that is concomitant with crashing for me(Nothing that is like this in the ksp.log file) entering Minmus's soi. I think that this is a bug with what ever communicates with Kopernicus to replace textures and stuff not getting the correct res set, or it may be a oddity with a .cfg file that I forgot about, There is also a incorrectly set or changed setting that you for got to reset or change with edge length in the "ParallaxGlobal.cfg" Its set to 8, not 25 unless the default is meant to be 8.

My .log file(from incident, Over writes previous logs)
[crsh(ksp).log](https://github.com/Gameslinx/Tessellation/files/5586063/crsh.ksp.log)

**Comment by Gertinin** [comment]
I am also willing to test versions that may have a fix.

**Comment by Gameslinx** [comment]
The texture resolutions are correct - That's just my Load On Demand code logging everything that it's working through.
Can you browse to AppData/LocalLow/Squad/KerbalSpaceProgram/ and upload your player-prev.log, please?
Your KSP.log does not evidence a crash, but that file might help

**Comment by Gertinin** [comment]
[Player-prev.log](https://github.com/Gameslinx/Tessellation/files/5587540/Player-prev.log)
There is my prev.log. Hope it helps.

**Comment by Gameslinx** [comment]
Unfortunately there's no evidence of a crash in either log - it just stops logging. This leads me to believe that Parallax is not the cause of the crash.
You mentioned Linux when you reported the crash, however the log says you're running Windows.
I'm afraid I'm not sure what caused this crash

**Comment by Gertinin** [comment]
oh, it says that I use windows because, proton (to my knowledge) satisfies dependencies for windows games on linux. I think it is probably my processor or ram for the processor I have a amd fx 8350 And I have 8gbs of ram. If any else here has 8gb and runs pop os 20.10, please tell me how stable it is.

**Comment by Gertinin** [comment]
Dm me the info on discord here: bbcraft#1286
