### ISSUE TITLE
Dependency checks failing on Linux

### ISSUE THREAD

**Issue by rkondratenko** [Gameslinx/Tessellation#16]
Not sure if it's Parallax Issue. If not, please redirect me to the faulty mod.
I'm using Steam with Linux and when Parallax dependencies are checked the paths are like "/opt/SteamLibrary/steamapps/common/Kerbal Space ProgGameData/Kopernicus/Config/System.cfg"
While the proper path is: "/opt/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/Kopernicus/Config/System.cfg". "ram/" is somehow missing. I solved it with a symlink.

Here is my full log (with symlink in place)
[KSP.log](https://github.com/Gameslinx/Tessellation/files/5597606/KSP.log)

**Comment by Gertinin** [comment]
Was this with wine or was it native? because I am interested in trying this if its native.

**Comment by Gertinin** [comment]
Thank you I was having this issue and forgot to report it, I will see if works for me.

**Comment by Gertinin** [comment]
Care to elaborate on how get Parallax to read the file?

**Comment by rkondratenko** [comment]
Just symlink a bad path to a real one:
```console
ln -s /opt/SteamLibrary/steamapps/common/Kerbal\ Space\ Program/GameData /opt/SteamLibrary/steamapps/common/Kerbal\ Space\ ProgGameData
```

**Comment by Gameslinx** [comment]
The file path is detected with this code:
`if (Application.platform == RuntimePlatform.OSXPlayer)
            {
                actualPath = Application.dataPath.Remove(Application.dataPath.Length - 16, 16) + "GameData/" + path;
            }
            else
            {
                actualPath = Application.dataPath.Remove(Application.dataPath.Length - 12, 12) + "GameData/" + path;
            }`
The executing directory appears to differ between Linux, MacOSX and Windows, which is quite annoying!
I can add another if statement which subtracts the correct amount of characters from the Application.dataPath for Linux as well.

Thank you for reporting - This will appear in the next update

**Comment by Gertinin** [comment]
Fun fact: to get better at Python I am working something that may fix the file system weirdness with Linux.

**Comment by rkondratenko** [comment]
@Gameslinx This path doesn't appear in the repository? Are there more files that are missing?

**Comment by Gameslinx** [comment]
This is in my build which is slightly ahead of the repo. The code exists but currently only does the removal of the last 12 characters for every platform.
The code is here: https://github.com/Gameslinx/Tessellation/blob/2d8ed4d72bf5a905f530fc7c378d5c0631612969/Loader/ParallaxSource.cs#L1918

**Comment by rkondratenko** [comment]
Why not use `KSPUtil.ApplicationRootPath + "GameData/"` ?
