### ISSUE TITLE
No textures on Linux

### ISSUE THREAD

**Issue by rkondratenko** [Gameslinx/Tessellation#17]
I'm using Steam with Ubunru Linux. There were some problems with Parallax startup (referenced in other issues), but I finally managed the mod to run with a few well-placed symlinks. However, I get no (transparent) terrain everywhere still.
I'm including my log below. Suspicious entries are:
```[LOG 18:05:48.629] [Parallax]////////////////////////////////////////////////
[LOG 18:05:48.629] [Parallax]////////////////Kerbin////////////////
[LOG 18:05:48.629] [Parallax]////////////////////////////////////////////////

[LOG 18:05:48.629] [Parallax] - Retrieved body node
[LOG 18:05:48.630] Critical error: Input was a string, but it should have been a float: Textures / normalSpecularInfluence
```
```
[EXC 18:05:48.869] KeyNotFoundException: The given key was not present in the dictionary.
        System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
        ParallaxShader.ParallaxLoader.GetShader (System.String name) (at <0e962ee0d677445f832ed458f7108ca3>:0)
        PQSModExpansion.GrassLoader.Start () (at <b6b3af8f70dd42d7adac8493f5bd45d3>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```
```[LOG 18:05:49.483] [Parallax] Subdivision Error:
System.NullReferenceException: Object reference not set to an instance of an object
  at PQSModExpansion.PQSMod_Subdivide.OnQuadBuilt (PQ quad) [0x00002] in <b6b3af8f70dd42d7adac8493f5bd45d3>:0 
```
```[WRN 18:06:25.584] ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
```
```[EXC 18:06:26.203] NullReferenceException: Object reference not set to an instance of an object
        ParallaxShader.Position.Update () (at <0e962ee0d677445f832ed458f7108ca3>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 18:06:26.384] NullReferenceException: Object reference not set to an instance of an object
        ParallaxShader.ParallaxOnDemandLoader.Update () (at <0e962ee0d677445f832ed458f7108ca3>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

[KSP.log](https://github.com/Gameslinx/Tessellation/files/5597628/KSP.log)

**Comment by Gertinin** [comment]
what dependencies are being listed out of Parralax(core), kopernicus, parallax stock textures. if one is satisfied, it will be green. Also please provide your ksp.log file to get help.

**Comment by rkondratenko** [comment]
The log file is attached to the end of the original message. 
Dependencies are green on loading: Kopernicus, Parallax (Core), Parallax (Stock Textures)

**Comment by Gameslinx** [comment]
The log errors are harmless - I forgot to clean them up in the last update - They will bhae fixed entirely in the next one
Linux and MacOSX currently have problems running the shader. I'm looking into it, but without a MacOSX / Linux computer I will struggle to make progress very quickly

This is a duplicate report, so I will close it. Feel free to re-open it if you have any ideas!

**Comment by rkondratenko** [comment]
@Gameslinx how does one debug it? I can try to find out what's happening inside if you can point where to look.

**Comment by Gameslinx** [comment]
It will be difficult to debug because I don't know how myself. I suspect it's to due with the shader using non-square matrices which causes OpenGL ES to be excluded from the build. Mac and Linux use OpenGL and not OpenGL ES, but the problem could be related.
I'm doing my best to get the shader working on those platforms - if something good comes up I'll let you know

**Comment by rkondratenko** [comment]
Ok. I have a Linux machine and have some skills as a software developer. I can help to chase this issue if you can tell me where to start.

**Comment by rkondratenko** [comment]
@Gameslinx  I managed to compile and run this on my Linux system. There's an issue with determining shader suffix for Linux, the condition there was (Application.platform == RuntimePlatform.WindowsPlayer && SystemInfo.graphicsDeviceVersion.StartsWith("OpenGL")). Is this for running under wine?
Also linux shaders don't work, Unity reports that shaders loaded from linux file are not supported on client system. If I swap it for macos shader file, the shaders are reported as supported. I then get transparent terrain and eventual crash in native code. There are other issues with `FlightGlobals.currentMainBody` being `null`. If I allow it to result in Exception, the game cannot load the main menu. If I just guard against it, the game works (with transparent terrain and crashes).

**Comment by Gameslinx** [comment]
I'll update the repo shortly with the fixed NRE spam (forgot an if check).
The shader itself doesn't work but I can't figure out why. 
It runs for DX11 and OpenGL in the UnityEditor - they're being built for DX11 and OpenGL too. There should be no reason why they're not supported, which is puzzling me a lot.

If you need the shader source code, message me on Discord ( Linx#0544 )
