### ISSUE TITLE
[Suggestion] Terrain collision - Smoothing

### ISSUE THREAD

**Issue by TheMightyDuckOfDoom** [Gameslinx/Tessellation#22]
While watching your work in progress videos about the terrain collision, I thought about ways to make the ride smoother, less bumpy.
An idea would be to do some sort of polynomial interpolation of multiple samples to gather a good approximation of the terrain's gradient. The sample points could be spaced depending on the surface speed of the rover/wheel. The faster the wheel travels, the more spaced out the samples get and thereby smoothing the terrain and when it is slow or standing still the interpolation could be quite accurate.

**Comment by eberkain** [comment]
What if I build a contraption with 30 wheels?  I think the solution needs to be the most performance friendly option.

**Comment by Gameslinx** [comment]
That is what a suspension does :)
