### ISSUE TITLE
1.1.1 Mun is just black, even in direct sunlight

### ISSUE THREAD

**Issue by matthewsanetra** [Gameslinx/Tessellation#23]
Hi!

I just installed the mod and the Mun's surface is just completely black.

I followed the installation instructions as in the README.

KSP.log: https://gist.github.com/matthewsanetra/0302eb007ec57ca25be0f49181eca104
ParallaxGlobal.cfg: https://gist.github.com/matthewsanetra/9671c64449ae3aac3e9c9f61e4afaa64

Thank you for your time!

**Comment by Gameslinx** [comment]
Should be fixed in the new Beta
