### ISSUE TITLE
Unable to Validate Installation

### ISSUE THREAD

**Issue by cfallon61** [Gameslinx/Tessellation#24]
Hello

Every time I boot KSP with Parallax installed (using bleeding edge Kopernicus and Parallax Stock Textures) I get errors saying that the dependencies aren't being met, even though they do in fact exist on my system. I've looked through the KSP.log file and it appears that perhaps there is a bug with the path construction. 

You can see the first example on line 277 where the path is `.../common/Kerbal Space ProgGameData/...` when it should be `.../common/Kerbal Space Program/GameData/...` 

Looking at the code, I think the issue might be something to do with line 2292 of ParallaxSource.cs incorrectly truncating the file path on linux. 

System Specs (if that's important):
Arch Linux: 5.9.14-arch1-1
RTX 3070
R9 3900x

I did install the mods according to the Parallax README - Parallax, Kopernicus, and ParallaxStockTextures are all in Gamedata as their own directories.

If I can provide any other information just let me know

[KSP.log](https://github.com/Gameslinx/Tessellation/files/5760894/KSP.log)

**Comment by Gameslinx** [comment]
Fixed in the current beta (~1 hour until updated)
