### ISSUE TITLE
Path string handling in ParallaxSource.cs

### ISSUE THREAD

**Issue by ofpkubi** [Gameslinx/Tessellation#25]
Hi,

As reported in KSP forums, the path calculation in ParallaxSource.cs (around row 2240) is faulty. 

actualPath = Application.dataPath.Remove(Application.dataPath.Length - 16, 16) + "GameData/" + path;

In Linux as the executable name (e.g., KSP.x86_64) is not 16 character (and the executable cannot be renamed).

Having a fixed length cut of the executable file name may work in certain circumstances, but it could lead to faults depending on how the game was started (CKAN, Steam, cmd line KSP.x86_64 or KSPLauncher.x86_64).

Without knowing Unity or .NET in detail, there are string handling methods, for sure, that can be used to cut the string at the last instance of a path separator character(s) (e.g., .NET String.LastIndexOf). Alternatively, many environments support  more advanced methods, such as "dirname".

**Comment by Gameslinx** [comment]
Fixed, thanks for the report :)
