### ISSUE TITLE
Minor Minmus texture tiling error.

### ISSUE THREAD

**Issue by TiberiusMars** [Gameslinx/Tessellation#27]
Minor: I think one of the "low" textures in Parallax_StockTextures\Minmus\PluginData has a tiling issue.

![Minmus Texture](https://i.imgur.com/IWY9lxh.jpg)

**Comment by TiberiusMars** [comment]
Unrelated, but I notice turning on lights on the surface drops my FPS from 70 to 32 lol.

**Comment by Gameslinx** [comment]
Thanks for the report, will correct for the release.
KSP uses ForwardRendering. Each light adds an additional render of the terrain, which tanks performance. Nothing I can do

**Comment by TiberiusMars** [comment]
I guess I should put less lights on my towers.
