### ISSUE TITLE
Tweakscale Support

### ISSUE THREAD

**Issue by eberkain** [Gameslinx/Tessellation#28]
When scaling landing legs to be maximum size, they have issues. 

https://gfycat.com/opulentdisastrousgrayling

https://gfycat.com/raregracefulhagfish

**Comment by Gameslinx** [comment]
If I was to increase the collider's size by the scale factor, would that sound like a good idea? The cubes would be larger and could interfere with other parts, though

**Comment by eberkain** [comment]
I think that would probably work fine.  Assuming the cubes stayed down at the ground. :)
