### ISSUE TITLE
Wheel just pop

### ISSUE THREAD

**Issue by aezarkones** [Gameslinx/Tessellation#29]
Wheel just randomly pop out when **speeding on Kerbin**. I think this i cause by PARLLAX colision system. Sending craft file.
[Zwiadowca I.zip](https://github.com/Gameslinx/Tessellation/files/5895998/Zwiadowca.I.zip) I was trying to look on stress on wheels but it have 0.4 and randomly pop.

**Comment by Gameslinx** [comment]
What surface were you speeding on and how fast?

**Comment by aezarkones** [comment]
Speed more than 16 m/s usualy closer 25 m/s. I test it on flat grass land near KSP center going in random directions (mostly after flip from launchpad same result wichout flip) pressing only foward key to test it not only when I turning and its not. When i testing it it was always one of four wheels i test it very loot and even found one place where it always get pop at speed < 19 m/s (test it 6-8 times in a row and get pop always somewhere in this place [one time all wheels survive]) First screen pop in less than 18 m/s secound screen about 16 m/s I can test it more if you need here some SS's and rover i used this time for testing (its simular to last one)
![Secound screenshot28](https://user-images.githubusercontent.com/2156075/106792975-27bfc800-6657-11eb-82b6-5476442d1045.png)
![Secound screenshot29](https://user-images.githubusercontent.com/2156075/106792980-28f0f500-6657-11eb-96ef-168a52afb669.png)
![First screenshot](https://user-images.githubusercontent.com/2156075/106792981-2a222200-6657-11eb-9dba-26cb237e21e2.png)
![First screenshot27POPPLACE](https://user-images.githubusercontent.com/2156075/106792991-2b534f00-6657-11eb-857c-2d73aa2d3c64.png)
[Rover.zip](https://github.com/Gameslinx/Tessellation/files/5920716/Rover.zip)

Thank you for your work, your mods are awsome! :D
