### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by jakedacatman** [Gameslinx/Tessellation#3]
See https://github.com/Gameslinx/BeyondHomePlanetMod/issues/9 (moving to here)

Basically on Linux the textures/shaders for Rhode at least are not loaded, yielding hot pink terrain. This can be worked around by renaming the OS X shader file (GameData/Parallax/Parallax-macosx.unity3d) to Parallax-linux.unity3d.

Ring textures are still missing.

**Comment by Gameslinx** [comment]
The ring shader isn't mine, so I cannot fix that. I've forwarded the issue to the Kopernicus folks.
KSP is wrongly detecting the platform of the user's PC.
It is detecting MacOSX as Linux. I'll be adjusting the shader files for the next update, then I'll close this issue. 

Feel free to re-open it if the problem persists.

**Comment by ffrank6217** [comment]
I'm still getting this problem but on windows. @jakedacatman 's fix doesn't seem to work for me, even after reinstalling the game. Taking a look at the logs, I think this may have something to do with the issue:

`[LOG 00:23:22.183] [Parallax] SOI changed, beginning transfer of surface textures for Kerbin
[LOG 00:23:22.183] [Parallax] Unloading 0 textures
[LOG 00:23:22.184] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/sea_sand00
[LOG 00:23:22.184] [Parallax]  - Texture doesn't exist, skipping: _SurfaceTexture with filepath: BeyondHome/Terrain/DDS/sea_sand00
[LOG 00:23:22.184] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/dry_sand00
[LOG 00:23:22.184] [Parallax]  - Texture doesn't exist, skipping: _SurfaceTextureMid with filepath: BeyondHome/Terrain/DDS/dry_sand00
[LOG 00:23:22.184] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/snow00
[LOG 00:23:22.184] [Parallax]  - Texture doesn't exist, skipping: _SurfaceTextureHigh with filepath: BeyondHome/Terrain/DDS/snow00
[LOG 00:23:22.184] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/cliff00
[LOG 00:23:22.184] [Parallax]  - Texture doesn't exist, skipping: _SteepTex with filepath: BeyondHome/Terrain/DDS/cliff00
[LOG 00:23:22.184] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/sea_sand01
[LOG 00:23:22.185] [Parallax]  - Texture doesn't exist, skipping: _BumpMap with filepath: BeyondHome/Terrain/DDS/sea_sand01
[LOG 00:23:22.185] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/dry_sand01
[LOG 00:23:22.185] [Parallax]  - Texture doesn't exist, skipping: _BumpMapMid with filepath: BeyondHome/Terrain/DDS/dry_sand01
[LOG 00:23:22.185] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/snow01
[LOG 00:23:22.185] [Parallax]  - Texture doesn't exist, skipping: _BumpMapHigh with filepath: BeyondHome/Terrain/DDS/snow01
[LOG 00:23:22.185] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/cliff01
[LOG 00:23:22.185] [Parallax]  - Texture doesn't exist, skipping: _BumpMapSteep with filepath: BeyondHome/Terrain/DDS/cliff01
[LOG 00:23:22.185] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/Rhode00
[LOG 00:23:22.185] [Parallax]  - Texture doesn't exist, skipping: _DispTex with filepath: BeyondHome/Terrain/DDS/Rhode00
[LOG 00:23:22.185] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/Rhode01
[LOG 00:23:22.185] [Parallax]  - Texture doesn't exist, skipping: _InfluenceMap with filepath: BeyondHome/Terrain/DDS/Rhode01
[LOG 00:23:22.185] [Parallax] Validating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/BeyondHome/Terrain/DDS/RhodeFog
[LOG 00:23:22.185] [Parallax]  - Texture doesn't exist, skipping: _FogTexture with filepath: BeyondHome/Terrain/DDS/RhodeFog
[LOG 00:23:22.187] Completed load on demand
[LOG 00:23:22.187] Loading 0 textures from disk took 0.004333496ms`

I looked at the DDS folder and all the files seem to be there, so idk what's wrong.

**Comment by Gameslinx** [comment]
You need to use Parallax 1.0.1 with Beyond Home, as BH has not updated yet
