### ISSUE TITLE
Parallax keeps re-calculating tesselation and colliders

### ISSUE THREAD

**Issue by 18Jonas18** [Gameslinx/Tessellation#31]
As seen in the video below for some reason this only happens on eve.

https://youtu.be/zsYgVU7DVFA
This causes [atleast for me] some lag spikes.

[KSP.log](https://github.com/Gameslinx/Tessellation/files/5935099/KSP.log)

**Comment by Gameslinx** [comment]
I believe I have a fix for this. I will be releasing it soon if all goes well. Thanks for the report
