### ISSUE TITLE
Big ship explode in air case PARLAX 

### ISSUE THREAD

**Issue by aezarkones** [Gameslinx/Tessellation#33]
Hi, Its me again. :/

Cant liftoff bcs when i did it my SSTO just explode in air idk its bcs i have lags (5-9fps) but it colide not first time with parlax in those places and some times on higer atiture (look screens). I sending some screens and logs to. If you need something more please ask. Thank you for your briliant plugins!

https://pastebin.com/rbqASzuu

![screenshot32](https://user-images.githubusercontent.com/2156075/107360479-477f4200-6ad6-11eb-9a9f-0b4b3a2d22bf.png)
![screenshot33](https://user-images.githubusercontent.com/2156075/107360563-67af0100-6ad6-11eb-8c1c-c412c3b86ab1.png)
![screenshot34](https://user-images.githubusercontent.com/2156075/107360569-68e02e00-6ad6-11eb-82bd-fe56f0dc8bad.png)
![screenshot35](https://user-images.githubusercontent.com/2156075/107360574-6a115b00-6ad6-11eb-98d8-dc31dcbb1bc8.png)
![screenshot36](https://user-images.githubusercontent.com/2156075/107362509-22400300-6ad9-11eb-94ab-9d18e726f599.png)
![screenshot37](https://user-images.githubusercontent.com/2156075/107362513-2409c680-6ad9-11eb-97c1-44fdc8db703b.png)
![screenshot38](https://user-images.githubusercontent.com/2156075/107362515-253af380-6ad9-11eb-8476-18eeebe7c90d.png)
![screenshot39](https://user-images.githubusercontent.com/2156075/107362520-2704b700-6ad9-11eb-8263-0ee5e9bad5a1.png)
![screenshot40](https://user-images.githubusercontent.com/2156075/107362526-28ce7a80-6ad9-11eb-9d71-8f156f94ab9b.png)
![screenshot41](https://user-images.githubusercontent.com/2156075/107362532-2a983e00-6ad9-11eb-9d3b-985eecc960ab.png)
![screenshot42](https://user-images.githubusercontent.com/2156075/107362537-2bc96b00-6ad9-11eb-9fb0-55dde4f5efbd.png)

**Comment by Gameslinx** [comment]
Thanks for reporting this. I'll fix this asap

**Comment by Gameslinx** [comment]
Fixed, should be all good in the next update :)
