### ISSUE TITLE
tessellationQuality = High/Higher Eve problem

### ISSUE THREAD

**Issue by aezarkones** [Gameslinx/Tessellation#38]
Hi, I know you hate me bcs thoes reports... Ok here you go:

`refreshRate = realtime //FPS value or "realtime"`
function in global config case some bugs in logs, only setting this value as int looks to work. 
```

'tessellationQuality = Higher			//Default = Higher
		//Options are: Low / Normal / High / Higher'

```
This cause some graphical bugs on Eve (planet i test this only there) look  ss's
Notice it at High values too I tested it on all resolutions of ReflectionSettings
There is problem sometimes u sink in ground as well  at thoes settings you can see it on on ss's too.
Sending config file too, you can see there my other settings. No errors in KSP.log. But you can check it too.

I dont check full planet only places on ss's.
**tessellationQuality Normal and Low looks to works fine for me.**

![screenshot4](https://user-images.githubusercontent.com/2156075/108980631-28fb7800-768c-11eb-81ec-f2659877bf20.png)
![screenshot3](https://user-images.githubusercontent.com/2156075/108980625-2731b480-768c-11eb-9ea4-bd985afbdea5.png)
![screenshot0](https://user-images.githubusercontent.com/2156075/108980602-20a33d00-768c-11eb-89bd-fe67ea42187e.png)
![screenshot01](https://user-images.githubusercontent.com/2156075/108980611-226d0080-768c-11eb-9380-e907a4c807cf.png)
![screenshot1](https://user-images.githubusercontent.com/2156075/108980612-2436c400-768c-11eb-97a3-ca305b2bf732.png)
![screenshot2](https://user-images.githubusercontent.com/2156075/108980618-2567f100-768c-11eb-9e0c-1895159ddf58.png)

Mods i have:
```
Mod DLLs found:
Stock assembly: Assembly-CSharp v0.0.0.0
ModuleManager v4.1.4.0
BAM v1.3.3.3 / v1.1.0.0
DistantObject v2.0.2.0
EasyVesselSwitch v2.2.7689.40431 / v2.2 for KSP v1.11+
KSPDev_Utils.2.4 v2.4.7504.27510 / v2.4 for KSP v1
MiniAVC-V2 v2.0.0.0
Atmosphere v1.11.2.1
CelestialShadows v1.11.2.1
CityLights v1.11.2.1
EVEManager v1.11.2.1
PartFX v1.11.2.1
PQSManager v1.11.2.1
ShaderLoader v1.11.2.1
Terrain v1.11.2.1
TextureConfig v1.11.2.1
Utils v1.11.2.1
_BuildManager v1.11.2.1
KerbalEngineer.Unity v1.0.0.0
KerbalEngineer v1.1.8.3
HyperEdit v1.5.8.0 / v1.5.8
Kopernicus.Parser v1.0.0.0
ModularFlightIntegrator v1.0.0.0 / v1.2.9.0
Kopernicus v1.0.0.0
KittopiaTech v1.0.0.0
DockingPortAlignmentIndicator v6.9.2.2
DPAI_RPM v1.0.0.2
ModuleDockingNodeNamed v1.0.0.2
PQSModExpansion v1.0.0.0
Parallax v1.0.0.0
ParallaxCollision v1.0.0.0
ParallaxInstallationChecker v1.0.0.0
PlanetShine v0.2.6.1
Restock v0.1.0.0
scatterer v0.723.0.0
SmokeScreen v2.8.14.0
Stock assembly: KSPSteamCtrlr v0.0.1.35
TextureReplacer v4.2.1.37427
TimeControl v2.10.0.0
KerbalAlarmClock v3.13.0.0
TransferWindowPlanner v1.7.2.0
TUFX v1.0.0.0

```
[log_and_cfg.zip](https://github.com/Gameslinx/Tessellation/files/6034907/log_and_cfg.zip)

Using HyperEdit v1.5.8.0 / v1.5.8 for tests. (this landing thing as you can see on ss's)

I find it when i try to fix all errors at KSP.log i check it preaty well only bug I cant figure out is from EVE plugin as you can see at log file.

Have nice day!
Ty for fantastic plugin!

**Comment by Gameslinx** [comment]
Thanks for reporting - This happens when the subdivisionLevel is pushed too high.
TessellationQuality = high / higher multiplies the subdivision level by 1.25 and 1.5 respectively - I will clamp this to stop this from happening on Eve.
If you want to fix this yourself, lower the subdivisionLevel in the IncreaseSubdivisionCount.cfg for Eve
