### ISSUE TITLE
Some terain spikes when I zoom out

### ISSUE THREAD

**Issue by aezarkones** [Gameslinx/Tessellation#39]
I will send you only ss's bcs i find it when I try to test **issue #38** on other planets
I thik it from Parallax but not sure. You can check log file from **issue #38**
I post it in next issue bcs its diferent thing i think. One ss's is from **Issue #38** as well I put it in bad folder sorry.

![screenshot1x](https://user-images.githubusercontent.com/2156075/108984774-97423980-7690-11eb-9aa7-e9586bb541df.png)
![screenshot2x](https://user-images.githubusercontent.com/2156075/108984780-98736680-7690-11eb-9839-20b0d65c1863.png)
![screenshot3x](https://user-images.githubusercontent.com/2156075/108984784-990bfd00-7690-11eb-9b2e-9fb1a0b84f66.png)
![screenshot4x](https://user-images.githubusercontent.com/2156075/108984789-9a3d2a00-7690-11eb-9afe-139a0d74c472.png)
![screenshot5](https://user-images.githubusercontent.com/2156075/108984791-9b6e5700-7690-11eb-9615-2058ee9d0136.png)
![screenshot6](https://user-images.githubusercontent.com/2156075/108984800-9c9f8400-7690-11eb-8d5c-181138e9da91.png)
![screenshotlathe](https://user-images.githubusercontent.com/2156075/108984808-9e694780-7690-11eb-9031-34a3183ff8a9.png)
![screenshotwut](https://user-images.githubusercontent.com/2156075/108984816-9f9a7480-7690-11eb-8259-08444ac05b59.png)
![screenshotx1](https://user-images.githubusercontent.com/2156075/108984821-a0330b00-7690-11eb-9fd5-d9ac060d0128.png)
![screenshotx5](https://user-images.githubusercontent.com/2156075/108984822-a1643800-7690-11eb-95e8-f5934c0d6e5b.png)

I test it on:

`tessellationQuality Low` btw

Thanks again for fantastic plugin!
Have nice day!

**Comment by Gameslinx** [comment]
Most of these are a result of you hyper editing and this is a bug that happens without Parallax installed. To fix, quicksave + quickload.
As for the issue on Eve, I responded to that on the other issue you opened
