### ISSUE TITLE
Unable to place deployable science

### ISSUE THREAD

**Issue by Luxyr** [Gameslinx/Tessellation#42]
![image](https://user-images.githubusercontent.com/5474643/109599361-e7c1f880-7acf-11eb-9b91-f945ad08090c.png)

When I attempt to deploy science on the surface of the Mun, it seems to not be finding the terrain. I've tried toggling "collide" on/off in the config and reloading, didn't make a difference.

**Comment by Luxyr** [comment]
Reducing the tessellationHeight to 1.0 for the Mun made it a little better, but it was still hard to find viable spots.

**Comment by Gameslinx** [comment]
The kerbal is too high off the ground. I will attempt to add a collision plane for the science part before it has been placed which should result in its height check working for the Parallax terrain, meaning you should be able to place it properly
