### ISSUE TITLE
Kerbal's in EVA coliding with Ship/ShipParts when jumping/flying over them.

### ISSUE THREAD

**Issue by aezarkones** [Gameslinx/Tessellation#44]
Hi I find new isue. :/ When jumping/flying over spaceship/parts in EVA kerbals just move them [I know you want to give my kerbals superpowers ^_^] even if not touch them (I think 1-6m above). Tested on fresh copy of paralax too. (Don't happen witout parallax). You can see it looking on 5,6,7 SS's especialy.

Log:
[KSP.log](https://github.com/Gameslinx/Tessellation/files/6113040/KSP.log)
SS's
![screenshot7](https://user-images.githubusercontent.com/2156075/110571517-eb9ced00-8157-11eb-9862-5de49e905fd3.png)
![screenshot8](https://user-images.githubusercontent.com/2156075/110571521-ecce1a00-8157-11eb-8d3b-35e56bc04583.png)
![screenshot9](https://user-images.githubusercontent.com/2156075/110571525-ee97dd80-8157-11eb-9c9e-ef7151af3001.png)
![screenshot10](https://user-images.githubusercontent.com/2156075/110571530-efc90a80-8157-11eb-9e91-524cd187ca96.png)
![screenshot11](https://user-images.githubusercontent.com/2156075/110571537-f192ce00-8157-11eb-8b44-332649a86b27.png)
![screenshot12](https://user-images.githubusercontent.com/2156075/110571540-f2c3fb00-8157-11eb-9c97-ead4d5f039de.png)
![screenshot13](https://user-images.githubusercontent.com/2156075/110571543-f48dbe80-8157-11eb-80e8-1960a1ad1a37.png)
![screenshot14](https://user-images.githubusercontent.com/2156075/110571550-f6578200-8157-11eb-9993-e182c36ad306.png)
![screenshot15](https://user-images.githubusercontent.com/2156075/110571554-f8214580-8157-11eb-9f9d-42bec8e434fa.png)
![screenshot16](https://user-images.githubusercontent.com/2156075/110571558-f9eb0900-8157-11eb-8085-b7aef2f57996.png)
![screenshot17](https://user-images.githubusercontent.com/2156075/110571562-fbb4cc80-8157-11eb-9511-0200b0e92fe2.png)
![screenshot18](https://user-images.githubusercontent.com/2156075/110571567-fce5f980-8157-11eb-8089-c3519d3ab6f3.png)
![screenshot19](https://user-images.githubusercontent.com/2156075/110571572-fe172680-8157-11eb-980c-baf5b49f64be.png)
![screenshot20](https://user-images.githubusercontent.com/2156075/110571577-ffe0ea00-8157-11eb-8682-739b2a60c359.png)
![screenshot21](https://user-images.githubusercontent.com/2156075/110571581-01121700-8158-11eb-8534-ac8425a3699f.png)

**Comment by aezarkones** [comment]
Oh alt+3 and now is clear what happen :O, I think it is this funy invincible box.
![screenshot61](https://user-images.githubusercontent.com/2156075/110587881-81467580-8174-11eb-8d19-6f22f4306e7b.png)

=====================================================================

And i findout #29 too it is this box. 
here you go more SS's:
![screenshot46](https://user-images.githubusercontent.com/2156075/110588456-53adfc00-8175-11eb-8920-6bd6b4353fc3.png)
![screenshot47](https://user-images.githubusercontent.com/2156075/110588458-5577bf80-8175-11eb-847a-359e9a4b16b3.png)
![screenshot48](https://user-images.githubusercontent.com/2156075/110588401-442eb300-8175-11eb-81ab-8746dde393f5.png)
![screenshot49](https://user-images.githubusercontent.com/2156075/110588407-45f87680-8175-11eb-8d0c-ab4787a756c9.png)
![screenshot50](https://user-images.githubusercontent.com/2156075/110588414-47c23a00-8175-11eb-83f6-a6fcf0d8226f.png)
![screenshot51](https://user-images.githubusercontent.com/2156075/110588422-498bfd80-8175-11eb-9e67-7bd3f56895ea.png)
![screenshot52](https://user-images.githubusercontent.com/2156075/110588429-4b55c100-8175-11eb-9608-e6435e57aa37.png)
![screenshot53](https://user-images.githubusercontent.com/2156075/110588437-4c86ee00-8175-11eb-93bb-fe5e98c682b3.png)
![screenshot54](https://user-images.githubusercontent.com/2156075/110588443-4e50b180-8175-11eb-954b-e1d6a08b7dd3.png)
![screenshot55](https://user-images.githubusercontent.com/2156075/110588446-501a7500-8175-11eb-9050-25c318716fb2.png)
![screenshot56](https://user-images.githubusercontent.com/2156075/110588453-51e43880-8175-11eb-8ae5-fc49e7b6233f.png)

**Comment by aezarkones** [comment]
My proposal:

Can you do this box afect only on part/kerbal it belong to? If not you need to recreate this. :/ (or you can find if other part is above vector you create [think it will be not good for big bases with lot of parts if loop not going all the parts anyways])
This box is to wild too. Do you test sphere for example( yep i know it afect on center of the wheel just thinking how it works with sphere I look at unity API)? 


Or try to use generated chunk of terain as you use in parallax (if this posible I think it is the simplest way and will fix lot of problems with parts placement I think, of course you should reduce some polygons in terain maby some optional thing in config for lower cpu/gpu usage) Idk but things on this SS's can be caused bcs terain going up and may be some cind wierd calculation by the program when terain go from 0m to 0.5m insta (in one physical frame of the game) at edge of this rock going up the hill.
Im bad at coding but want to try some fixes by my selpf. Can you tell me what exactly library you use? (I wach your tutorial on youtube how to create plugin and yep it works for me). I love to bug testing things, not exactly interested in coding im graphics artist. I know little  more then nothing about coding but will be lot easier for some testing for me, and can help you to improve this fantastic plugin.

**Comment by aezarkones** [comment]
Next thing when i change vechicles witch "[" & "]" on Mun (loading physics fast around) this cause to flip over or fly away my base buildings, rovers, kerbals and stuff on surface. This is litle bit anoing :/.

**Comment by EmeraldWither** [comment]
![output_48vVI5](https://user-images.githubusercontent.com/68785503/110793007-211e0500-8242-11eb-8abd-c80b9b3f3e38.gif)
![Webp net-gifmaker](https://user-images.githubusercontent.com/68785503/110793295-75c18000-8242-11eb-897f-754ef4560f03.gif)
Converted to GIF's so you can tell what is going on.

**Comment by Gameslinx** [comment]
This should be fixed now. I will release an update in a few days.
