### ISSUE TITLE
White Textures

### ISSUE THREAD

**Issue by hurstiam** [Gameslinx/Tessellation#46]
When loading into a new save, there is no textures or colors. The area around the KSC is bright white. This is on a fresh ksp install containing only this mod and its dependencies. Any help would be appreciated.

**Comment by EmeraldWither** [comment]
If this is what you are experiencing, then gameslinx said this in another issue:
https://github.com/Gameslinx/Tessellation/issues/41#issuecomment-792316333

"You do not meet the following minimum system requirements: Shader Model 5.0, GT 960M
You cannot run the Parallax shader without being on Shader Model 5.0 - You are using Shader Model 4.6.
You need a dedicated GPU to run this mod"

**Comment by hurstiam** [comment]
It appears to be the same issue, but my graphics card has a shader model of 6.4. I am using the most recent version of Kopernicus UBE and Parallax, even when these are the only mods installed, I'm encountering this issue.
![8A99EE2A-1AD4-40BE-BA3D-584D5857CF7F_1_105_c](https://user-images.githubusercontent.com/80738978/111316480-ad14a000-8639-11eb-8679-c1707d2fde70.jpeg)
![Image 3-16-21 at 9 13 AM](https://user-images.githubusercontent.com/80738978/111316518-b69e0800-8639-11eb-9872-d99526ccd918.jpeg)
![Image 3-16-21 at 9 23 AM](https://user-images.githubusercontent.com/80738978/111316556-bdc51600-8639-11eb-9d8d-2ed9d885fe44.jpeg)

**Comment by EmeraldWither** [comment]
Is your terrain set to high?

**Comment by hurstiam** [comment]
Yes

**Comment by Gameslinx** [comment]
I need your KSP.log file please

**Comment by hurstiam** [comment]
I did a fresh install of the game and the mod/dependencies to hopefully clean it up a bit for you.
[KSP.log](https://github.com/Gameslinx/Tessellation/files/6161201/KSP.log)

**Comment by EmeraldWither** [comment]
A new version has been released, try using that.

**Comment by hurstiam** [comment]
Just tried the updated version with no change.
