### ISSUE TITLE
Texture won't load

### ISSUE THREAD

**Issue by William1014** [Gameslinx/Tessellation#48]
It seems like the texture won't load, I've checked the versions and there was no problem, Kopernicus BL was also in the gamedata. Help!
![image](https://user-images.githubusercontent.com/59858797/112088844-7acfe900-8bcb-11eb-8aee-6ca3d24b0fc8.png)

**Comment by EmeraldWither** [comment]
Can we see your gamedata folder?

**Comment by Gameslinx** [comment]
Can you send your KSP.log?

**Comment by MaximWE** [comment]
I have the same issue. 
Here´s the log.
[KSP.log](https://github.com/Gameslinx/Tessellation/files/6215724/KSP.log)

**Comment by MaximWE** [comment]
I used KopernicusBE_19 and the issue is gone.

**Comment by EmeraldWither** [comment]
Problem was that you were using a Kopernicus that was meant for 1.10, and not 1.11.
