### ISSUE TITLE
Textures appear to be white/bright and featureless.

### ISSUE THREAD

**Issue by Alioth81** [Gameslinx/Tessellation#49]
Textures appear to be white/bright and featureless.

Logs attached and screenshots of Minmus and Kerbin that illustrate the problem. I removed all mods except for Kopernicus and parallax (there are some errors because of missing parts, however the error is also present when starting a new game)

Graphics card is a Geforce GTX 1070 with nvidia driver 461.92

[Player.log](https://github.com/Gameslinx/Tessellation/files/6218224/Player.log)
[KSP.log](https://github.com/Gameslinx/Tessellation/files/6218228/KSP.log)
![parallax-test](https://user-images.githubusercontent.com/34184766/112770669-0a402680-9028-11eb-892f-e63444790b8b.jpg)
![parallax-testMinmus](https://user-images.githubusercontent.com/34184766/112770690-322f8a00-9028-11eb-9276-a8716a5ee3ca.jpg)

**Comment by EmeraldWither** [comment]
Are you sure that you are using the latest version of Parallax? Is your terrain quality set to "High"?

**Comment by Alioth81** [comment]
![settings](https://user-images.githubusercontent.com/34184766/112841195-7fe7d900-90a0-11eb-9fcc-7064a0ef0b79.jpg)
 Those are the settings.
I put one setting that was on default to high but it made no difference and it looks like the screenshots posted above

**Comment by Gameslinx** [comment]
Missing ModularFlightIntegrator that comes with Kopernicus
