### ISSUE TITLE
Crafts passing through terrain (1.2.3)

### ISSUE THREAD

**Issue by Goldknight01** [Gameslinx/Tessellation#50]
![20210401175547_1](https://user-images.githubusercontent.com/60305054/113358490-df99ea80-9313-11eb-9e21-2626c2a71d7c.jpg)

![20210330115938_1](https://user-images.githubusercontent.com/60305054/113359834-97c89280-9316-11eb-9078-2f4345b03337.jpg)

Craft passes through the terrain layer.

![Screenshot (168)](https://user-images.githubusercontent.com/60305054/113359527-f2adba00-9315-11eb-997b-28a424d39d00.png)
![Screenshot (169)](https://user-images.githubusercontent.com/60305054/113359532-f5101400-9315-11eb-9fed-780b01e35a7a.png)

When on EVA the craft becomes unstable and destroys itself.

Any idea what could be causing this? I installed the mod and updated it using CKAN, so everything should hopefully be installed correctly.

Here is the KSP log file:

[KSP.log](https://github.com/Gameslinx/Tessellation/files/6246729/KSP.log)

**Comment by Gameslinx** [comment]
Crafts without wheels or landing gear are supposed to do this
