### ISSUE TITLE
Landing legs clipping and jumping around on terrain

### ISSUE THREAD

**Issue by MrGuccu** [Gameslinx/Tessellation#51]
I love this mod for the visuals, but it has made landing on planets basically impossible. Let me explain, when I try and land on a planet, the whole craft basically starts bumping around violently, but eventually I am able to get it to land. As soon as I go EVA, the whole thing starts jumping around yet again, and then basically it gets to the point where it jumps up so high it crashes back into the ground. I've had this happen multiple times, and it's really frustrating. Here are some examples:
![image](https://user-images.githubusercontent.com/48893937/113416389-d7c75e00-9386-11eb-88bc-49e36cc946ff.png)
Eve base after clicking "fly" in tracking station, basically exploded and evaporated.

https://user-images.githubusercontent.com/48893937/113417339-cc753200-9388-11eb-9c8f-eee901f41b47.mp4
Demonstrating how things on landing legs seem to jump around like crazy. 

![image](https://user-images.githubusercontent.com/48893937/113417457-0cd4b000-9389-11eb-9246-51cbd9489aca.png)
This is what my KSP Directory looks like.

![image](https://user-images.githubusercontent.com/48893937/113417487-1d852600-9389-11eb-888c-16669fb7ded6.png)
![image](https://user-images.githubusercontent.com/48893937/113417504-283fbb00-9389-11eb-9eb3-04783b59ee92.png)
This is what my Game data directory looks like with the mods. 

What should I do? I really cant land like this, and it's driving me crazy. Is there some incompatible mods I have? Any help would be great :)

**Comment by Gameslinx** [comment]
Outdated version, closed
