### ISSUE TITLE
White box showing up after a kerbal fell

### ISSUE THREAD

**Issue by vinix38** [Gameslinx/Tessellation#52]
KSP version 1.11.2
Parallax version 1.2.3

I launched a craft on the launchpad, then I made a Kerbal quit its EVA chair. The Kerbal glitched a bit through the vessel (as expected, stock behaviour), then landed on the pad. At this point I noted the white box had showed underneath the vessel.

![image](https://user-images.githubusercontent.com/68441743/113476972-34a63f80-947f-11eb-9991-2529a5744d33.png)

The bug is not a visual one, you can bump on it and even climb it.

![image](https://user-images.githubusercontent.com/68441743/113476993-51427780-947f-11eb-8099-4ea3b56f0958.png)

Also, there was a log spam from Parallax.

> [EXC 13:08:03.370] NullReferenceException: Object reference not set to an instance of an object
	ParallaxCollision.ParallaxPhysics.FixedUpdate () (at <105395616d6b4c1b87418678576c5658>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)

This bug is quite rare, and seems to be triggered by Kerbal falling like they are not supposed to

**Comment by vinix38** [comment]
![image](https://user-images.githubusercontent.com/68441743/113518062-3279d900-9584-11eb-9f54-25b8fc5c38b0.png)

It happened again, when the kerbal left his seat in mid air

**Comment by cosmicnotepin** [comment]
Similar things happen for me, i get white cubes that explode my crafts, most often when i leave EVA chairs. One time the white cubes kept spawning constantly under (part of) my craft while it was falling back to the surface.
