### ISSUE TITLE
Kerbals walk on air on Mun

### ISSUE THREAD

**Issue by Mercuri** [Gameslinx/Tessellation#54]
Haven't tried this on other planets or anything yet but my Kerbals kept floating in the air and happily running around.  Removing the Parallax mod fixed the issue.

https://user-images.githubusercontent.com/4699107/115214395-77e3ed80-a0d0-11eb-897a-431e74babdc5.mp4

**Comment by EmeraldWither** [comment]
Logs?

**Comment by Mercuri** [comment]
My bad, I knew I forgot something.  This is the bit that seemed relevant to the EVA.  Full logs attached.

`[LOG 09:08:23.085] [Parallax Physics] Restarting after unpack...
[LOG 09:08:23.085] Starting physics!
[ERR 09:08:23.085] Tag: Highlands is not defined.

[LOG 09:08:23.085] [Parallax Physics] Body changed! Getting new values...
[LOG 09:08:23.085] [Parallax Physics] Success!
[LOG 09:08:23.085] Restarting the components for: landingLeg1
[LOG 09:08:23.086] Using foot
[LOG 09:08:23.086] Using foot
[LOG 09:08:23.086] Using foot
[LOG 09:08:23.086] [Parallax Collisions] Restarted wheels
[LOG 09:08:23.087] [Parallax Physics] Restarting after unpack...
[LOG 09:08:23.087] Starting physics!
[ERR 09:08:23.087] Tag: Highlands is not defined.

[LOG 09:08:23.087] [Parallax Physics] Body changed! Getting new values...
[LOG 09:08:23.087] [Parallax Physics] Success!
[LOG 09:08:23.087] Restarting the components for: landingLeg1
[LOG 09:08:23.087] Using foot
[LOG 09:08:23.087] Using foot
[LOG 09:08:23.087] Using foot
[LOG 09:08:23.087] [Parallax Collisions] Restarted wheels
[LOG 09:08:23.088] [Parallax Physics] Restarting after unpack...
[LOG 09:08:23.088] Starting physics!
[ERR 09:08:23.088] Tag: Highlands is not defined.

[LOG 09:08:23.088] [Parallax Physics] Body changed! Getting new values...
[LOG 09:08:23.088] [Parallax Physics] Success!
[LOG 09:08:23.088] Restarting the components for: landingLeg1
[LOG 09:08:23.088] Using foot
[LOG 09:08:23.088] Using foot
[LOG 09:08:23.088] Using foot
[LOG 09:08:23.088] [Parallax Collisions] Restarted wheels
[LOG 09:08:23.088] [Parallax Physics] Restarting after unpack...
[LOG 09:08:23.088] Starting physics!
[ERR 09:08:23.088] Tag: Highlands is not defined.

[LOG 09:08:23.088] [Parallax Physics] Body changed! Getting new values...
[LOG 09:08:23.088] [Parallax Physics] Success!
[LOG 09:08:23.088] Restarting the components for: landingLeg1
[LOG 09:08:23.088] Using foot
[LOG 09:08:23.088] Using foot
[LOG 09:08:23.089] Using foot
[LOG 09:08:23.089] [Parallax Collisions] Restarted wheels
[LOG 09:08:23.113] [UIMasterController]: ShowUI
[LOG 09:08:30.208] [Parallax Physics] New vessel located: kerbalEVA_female_Future(Clone)(Clone)
[LOG 09:08:30.210] 4/19/2021 9:08:30 AM,AmpYear,OnVesselCreate
[LOG 09:08:30.210] [RemoteTech] SatelliteManager: OnVesselCreate(00000000-0000-0000-0000-000000000000, )
[LOG 09:08:30.230] [EFX] OnCrewOnEva()
[LOG 09:08:30.230] [EFX] Contains()
[WRN 09:08:30.231] [EFX] EvaContainer.Load(kerbalEVAfemaleFuture (Valentina Kerman))
[WRN 09:08:30.231] [EFX] EvaSettings.LoadEva(kerbalEVAfemaleFuture (Valentina Kerman))
[LOG 09:08:30.235] [Part:MEMLander (id=F1030070781)#Module:19] Items transfer | source seat: 0
[LOG 09:08:30.235] [Part:MEMLander (id=F1030070781)#Module:19] Items transfer | destination: [Part:kerbalEVAfemaleFuture (Valentina Kerman) (id=F1006071566)]
[LOG 09:08:30.265] [FlightGlobals]: ProtoPartSnapShot persistentId changed from 2080417331 to 1975754443. Vessel persistentId 0
[LOG 09:08:30.265] [FlightGlobals]: ProtoPartSnapShot persistentId changed from 1684667019 to 2448710137. Vessel persistentId 0
[LOG 09:08:30.268] [AirlockPlus|BoardingPass] INFO: EVA_Board key is B
[LOG 09:08:30.268] Look rotation viewing vector is zero
[LOG 09:08:30.269] Look rotation viewing vector is zero
[LOG 09:08:30.279] [ModularFlightIntegrator] MFI Start
[LOG 09:08:30.279] [ModularFlightIntegrator] Start. VesselModule on vessel : 
  ModularFlightIntegrator
  AxisGroupsModule
  CometVessel
  CommNetVessel
  BetterBurnTimeData
  RPMVesselComputer
  ParallaxPhysicsManager
  PartEventsManager
  VesselModuleSave

[LOG 09:08:30.279] Starting physics!
[ERR 09:08:30.279] Tag: Highlands is not defined.

[LOG 09:08:30.293] [Parallax Physics] Body changed! Getting new values...
[LOG 09:08:30.293] [Parallax Physics] Success!
[LOG 09:08:30.293] Restarting the components for: kerbalEVAfemaleFuture (Valentina Kerman)
[LOG 09:08:30.294] [Parallax Collisions] Restarted wheels
[LOG 09:08:30.333] [FLIGHT GLOBALS]: Switching To Vessel Valentina Kerman ---------------------- 
[LOG 09:08:30.335] [RemoteTech] OnVesselSwitching - from: Rigel I Lander to: Valentina Kerman
[LOG 09:08:30.335] Detected switch from dockingPort3 (Rigel I Lander) (Vessel) to kerbalEVAfemaleFuture (Valentina Kerman) (Vessel). Request camera stabilization.
[LOG 09:08:30.336] [PlanetariumCamera]: Focus: Valentina Kerman
[LOG 09:08:30.357] 4/19/2021 9:08:30 AM,AmpYear,AYController onVesselChange New:kerbalEVAfemaleFuture (Valentina Kerman) (8aef6182-994b-46c9-ad97-6288511e3ace) Old:c378617b-5796-43a1-b286-3a349dffb0b1
[LOG 09:08:30.358] 4/19/2021 9:08:30 AM,AmpYear,AYController active vessel 8aef6182-994b-46c9-ad97-6288511e3ace
[LOG 09:08:30.358] 4/19/2021 9:08:30 AM,AmpYear,Not a vessel type AmpYear is interested in
[LOG 09:08:30.359] [RemoteTech] OnVesselChange - new vessel: Valentina Kerman
[LOG 09:08:30.359] Fix camera focus while keeping its position
[LOG 09:08:30.361] [BetterBurnTime] Vessel changed to Valentina Kerman
[LOG 09:08:30.439] 4/19/2021 9:08:30 AM,KerbalAlarmClock,Vessel Change from 'Rigel I Lander' to 'Valentina Kerman'
[LOG 09:08:30.441] [KS3P]: Switch to profile "Astronomer's Visual Pack (Flight)"`

[KSP.log](https://github.com/Gameslinx/Tessellation/files/6336280/KSP.log)

**Comment by gilbertohasnofb** [comment]
> Haven't tried this on other planets or anything yet

I can confirm I see the same issue on both the Mun and Minmus.

Also, while walking around either of the two bodies, pressing space to jump will allow you to jump normally but turning RCS on and holding shift will cause you ascend _really_ slowly. 

The issue also seem to affect the deployed scientific equipment from the Breaking Ground DLC. Without Parallax, equipment can be put down anywhere, but with Parallax I often have to walk around to find a place where they are allowed to be put down. I've also seen small equipment (lamps) take off and fly away as soon as I put them down (probably due to some sort of collision detection?).

**Comment by Gameslinx** [comment]
Thanks guys. Fixed for the next update

**Comment by gilbertohasnofb** [comment]
@Gameslinx Thanks for fixing this! Do you have some idea of when the next update will be out?

**Comment by Gameslinx** [comment]
Well, by "fixed" I've removed the collisions. Hard to explain, but the detail has been massively improved in the next update and so the displacement doesn't need to be as extreme. This means that the collisions is no longer necessary and still looks good without (no floating)
