### ISSUE TITLE
White cube on Mun surface and when leaving a craft's physics range

### ISSUE THREAD

**Issue by asdfCYBER** [Gameslinx/Tessellation#55]
I encountered this issue the day before yesterday, I landed on the Mun and deployed a rover with external seats and surface science modules. After driving around and returning a dropped landing stage exploded similar to #50, and I noticed a white cube a hundred or so meters away:

![20210505182158_1](https://user-images.githubusercontent.com/33639328/117410767-27afbc80-af13-11eb-800a-579cb363c97b.jpg)
Exploded craft (remaining engine on the left)

![20210505182557_1](https://user-images.githubusercontent.com/33639328/117410980-604f9600-af13-11eb-9104-78137639105e.jpg)
Rover near white cube on surface

This is likely related to #52. When returning to orbit, my lander collided with a white cube. This happened again after loading a quicksave, but didn't happen when I stayed at roughly 50 m/s until beyond the physics range of crafts remaining on the surface.

![20210505183424_1](https://user-images.githubusercontent.com/33639328/117413052-cccb9480-af15-11eb-9148-1dc23947781e.jpg)
Collision with Cube

![20210505183437_1](https://user-images.githubusercontent.com/33639328/117413121-dce37400-af15-11eb-9d1f-204b10acd31d.jpg)
The cube and distance to objects on the surface

I uploaded the `KSP.log` and `Player.log` for both events [here](https://pizo.stackstorage.com/s/3xSXlJsKG0k6kwzv) (the logs are _large_). I also added the quicksave (I think ReStock, ReStock Plus and Near Future Electrical are the only mods I used in these crafts, but I could be wrong).

I also encountered #54 and #42 for what that's worth.

**Comment by asdfCYBER** [comment]
![20210507210719_1](https://user-images.githubusercontent.com/33639328/117512079-2e7c1500-af8f-11eb-9f68-c7b30a06ab43.jpg)

Just had the same thing happen on Minmus

**Comment by Gameslinx** [comment]
Part of collisions. Fixed in the next update
