### ISSUE TITLE
Extreme lag on surface of Mun

### ISSUE THREAD

**Issue by JackIt999** [Gameslinx/Tessellation#56]
Running ksp 1.11.2 (tested on 1.11.1 as well), Stock system with stock parallax textures. No other mods except for spectra. When I am within about 100m of the surface of the Mun my framrate drops like a brick and I have severe input lag.

**Comment by JackIt999** [comment]
nvm it was planetshine being wack

**Comment by SpaceArchitecture** [comment]
How did you fix it ?
