### ISSUE TITLE
Texture doesn't exist

### ISSUE THREAD

**Issue by dawid05** [Gameslinx/Tessellation#57]
When installing Parallax and Parallax Stock Planet Textures on macOS through CKAN, I encountered an error where the game fails to detect textures because it is searching the wrong directory.

In the KSP log, it says 'texture doesn't exist' and shows that it's scanning KSP.app/GameData/Parallax_StockTextures. However, the files are actually in GameData/Parallax_StockTextures. The textures would appear as white due to this. I was able to get around this by creating a GameData folder inside KSP.app and copying the textures mod there, but this seems to be a problem with the Parallax mod itself using the wrong directory structure as KSP.app is not meant to be modified.

**Comment by belpyro** [comment]
The same issue. Fixed by myself. Issue depends on wrong way to path creation.
` public void ValidatePath(string path, string name)
        {
            string actualPath = "";
            if (Application.platform == RuntimePlatform.OSXPlayer)
            {
                actualPath = Application.dataPath.Remove(Application.dataPath.Length - 16, 16) + "GameData/" + path;
            }
            else if (Application.platform == RuntimePlatform.WindowsPlayer)
            {
                actualPath = Application.dataPath.Remove(Application.dataPath.Length - 12, 12) + "GameData/" + path;
            }
            else
            {
                actualPath = Application.dataPath.Remove(Application.dataPath.Length - 16, 16) + "GameData/" + path;
            }`
Dear author. Please don't use hardcoded length for path. If you would like I can share my solution. I wouldn't like to create PR because repository too huge for clone and simple fix. Best regards!

**Comment by Gameslinx** [comment]
Fixed, releasing in next update
