### ISSUE TITLE
Potential incompatibility with Sigma Dimensions

### ISSUE THREAD

**Issue by Ackons** [Gameslinx/Tessellation#59]
I have found an issue in which (what I guess to be Sigma Dimensions) is causing a terrain flickering issue on Kerbin, both in flight and in the KSC menu. Attached is an image showing it in flight fully zoomed out, an MP4 of the issue in the KSC menu (same as inflight) and my KSP.log

![unknown](https://user-images.githubusercontent.com/24395436/124797976-df1b7c00-df20-11eb-94ee-26a1ecf37a8f.png)

https://user-images.githubusercontent.com/24395436/124797999-e478c680-df20-11eb-847d-c0e666d89dd8.mp4

[KSP.log](https://github.com/Gameslinx/Tessellation/files/6778844/KSP.log)

**Comment by Gameslinx** [comment]
Try the most recent scatterer version and let me know if the problem still persists

**Comment by Ackons** [comment]
I'll try in a little bit when I get to my computer

**Comment by Ackons** [comment]
Latest scatterer has fixed. I am having  an issue on Duna where my rover just keeps going up and the terrain randomly changes but I have closed the game for now and it will take too long to reopen to capture video

**Comment by Gameslinx** [comment]
Set this to true: useDepthBufferMode = False
