### ISSUE TITLE
Somethings wrong

### ISSUE THREAD

**Issue by m0a9r1c1el** [Gameslinx/Tessellation#60]
so yeah this is what it looks like, also it says i have an incompatible ksp version but i have 1.12.1

![Screenshot_1](https://user-images.githubusercontent.com/40620642/124808421-37716e80-df5f-11eb-8983-49319d9388d0.png)
![20210707200551_1](https://user-images.githubusercontent.com/40620642/124808467-4526f400-df5f-11eb-923b-717eb55f3808.jpg)
![20210707200554_1](https://user-images.githubusercontent.com/40620642/124808472-45bf8a80-df5f-11eb-817a-7b9c6e41344c.jpg)
![20210707200557_1](https://user-images.githubusercontent.com/40620642/124808473-45bf8a80-df5f-11eb-9e26-93066362555d.jpg)

here is my log [KSP.log](https://github.com/Gameslinx/Tessellation/files/6779230/KSP.log)

amazing work on the textures btw i hope this will be fixed soon :)

**Comment by Ackons** [comment]
I was having this issue but was thinking it was my sigma dimensions. Seeing this makes me think it could be something else. I also posted this issue, once something in common can be found in our logs we can discover what is really causing this

**Comment by Gameslinx** [comment]
Can you upload your Scatterer config? It's located in scatterer/config/config.cfg

**Comment by m0a9r1c1el** [comment]
[config - Copy.txt](https://github.com/Gameslinx/Tessellation/files/6780230/config.-.Copy.txt)
 renamed it to .txt for uploading. might be something with my config because i dont use the standart configuration im using the one that allows me to use msaa anti aliasing

**Comment by Gameslinx** [comment]
Set this to true: useDepthBufferMode = False

**Comment by m0a9r1c1el** [comment]
yeah i prefer msaa, im just gonna use the previous version of parrallax which worked fine with depth buffer
