### ISSUE TITLE
Parallax only loads a blank alpha texture on startup

### ISSUE THREAD

**Issue by BillKerm** [Gameslinx/Tessellation#61]
![image](https://user-images.githubusercontent.com/87102207/124843707-5d8b1480-df47-11eb-9169-1400823c84c9.png)
![image](https://user-images.githubusercontent.com/87102207/124843772-86aba500-df47-11eb-826d-93c64c98a4e9.png)

Have not tested this with the stock textures, but in Beyond Home 1.5.2 Parallax just renders this blank alpha texture instead of the normal surface textures, at least according to the logs.

KSP.log also reports that Parallax is not supported on KSP 1.12.1 for some reason.

This error also comes up multiple times in the logs, presumably when trying to render things near the active vessel:
`[EXC 16:18:45.175] NullReferenceException: Object reference not set to an instance of an object
	Parallax.ParallaxInFlightOperations.CheckIfBodySwitched (System.String bodyName) (at <1185d49058c34b4d8f81e5f3264cf3fb>:0)
	Parallax.ParallaxInFlightOperations.Update () (at <1185d49058c34b4d8f81e5f3264cf3fb>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`
	
For some reason GitHub won't let me send the full log file, so here's a mediafire link:
https://www.mediafire.com/file/1jxsnnl8pq6m5er/KSP.log/file

**Comment by Folkoer** [comment]
Got the same problem.
Did you find any fix yet?

**Comment by seasonedcurlys** [comment]
I also have this problem

**Comment by Gameslinx** [comment]
Use ballisticfox's BH fork and Parallax 1.3.1 or roll back to Parallax 1.0.1
