### ISSUE TITLE
Z-Fighting Issue with EVE's Cities on 1.3.0

### ISSUE THREAD

**Issue by Phrenk12** [Gameslinx/Tessellation#62]
I'm not sure if this is exactly "Z-Fighting" but it looks like it. Similar problem to [these](https://github.com/Gameslinx/Tessellation/issues/59) [two](https://github.com/Gameslinx/Tessellation/issues/60). However, the problem seems to only affect the EVE's cities. It's especially bad at night, when the city lights come on. When I switch back to 1.2.3, the issue is no longer present.  I do not have Sigma Dimensions and I have useDepthBufferMode = True in Scatterer

![z fighting](https://user-images.githubusercontent.com/87110679/124866198-03f80980-df8a-11eb-947c-b5a545065a52.png)

Here's a video to the problem

https://streamable.com/g91j0u

**Comment by m0a9r1c1el** [comment]
you have to disable depth buffer for the new verison, sucks but yeah. im just gonna use the previous version

**Comment by Gameslinx** [comment]
Fixed as of 2.0.0
