### ISSUE TITLE
Getting some weird surface glitches

### ISSUE THREAD

**Issue by EIonMask** [Gameslinx/Tessellation#63]
I believe this might be an issue with scatterer, I have the most recent scatterer and I have made useDepthBufferMode = False.
I am unsure how this is to be fixed?

![Screenshot (491)](https://user-images.githubusercontent.com/80643143/124932656-2b3aef00-dffb-11eb-8b8d-b2a2c63e1ae4.png)
![Screenshot (489)](https://user-images.githubusercontent.com/80643143/124932667-2d04b280-dffb-11eb-856d-20dfe12418d0.png)
![Screenshot (490)](https://user-images.githubusercontent.com/80643143/124932671-2e35df80-dffb-11eb-88de-77a19e7ffe3f.png)

**Comment by Ackons** [comment]
If you reinstall the latest scatterer after deleting the old one it SHOULD fix. That's what it did for me anyways

**Comment by EIonMask** [comment]
Fixed it by making:
 useDepthBufferMode = True
