### ISSUE TITLE
Same type of issue but only happened on citylights

### ISSUE THREAD

**Issue by Chromiumor** [Gameslinx/Tessellation#64]
Hi Linx, I encountered with a weird issue after updating to 1.3.0 version of Parallax. The issue is quite similar to [https://github.com/Gameslinx/Tessellation/issues/60](url) and [https://github.com/Gameslinx/Tessellation/issues/63](url) but only happened on the citylight layer. Pictures listed below shows this point.
![_ BLYOH9JNO9%7BA6%8@7VE](https://user-images.githubusercontent.com/53251430/124959329-ad540380-e04d-11eb-9c56-6a0432ccdfa9.png)
I have already installed the latest scatterer and enabled the Depth Buffer mode but the issue still exists...

**Comment by Gameslinx** [comment]
Fixed as of 2.0.0
