### ISSUE TITLE
Blank squares appearing 

### ISSUE THREAD

**Issue by 18Jonas18** [Gameslinx/Tessellation#65]
I don't know why this keeps happening but it only happens when I try to use my custom config for JNSQ.
This doesn't happen for normal Parallax in the stock system in version 1.12, only applies to JNSQ [as far as I am aware]
Don't know if it's a user error or some kind of other problem.

https://www.youtube.com/watch?v=HoSVkWbJhZk&ab_channel=Jonas
https://drive.google.com/file/d/1cqXkkZO49RoTxdCMFCGifPldAhHYlN8p/view?usp=sharing

**Comment by Gameslinx** [comment]
Fixed in 2.0.0
