### ISSUE TITLE
Floating/removal craft bug

### ISSUE THREAD

**Issue by NightShift10125** [Gameslinx/Tessellation#66]
A few times now I've crashed a few crafts (mostly planes) into kerbin during their first flight, I've noticed a bug where sometimes if a part is destroyed the game treats it like the root part and snaps the camera to the impact site.
Meanwhile the rest of the craft ignores gravity becomes forgotten by the game, the craft and it's crew are just removed from the game world, the crew isn't killed just reassigned to an eternal mission.
I assume it's cased by my high settings for the mod but other than that I'm unsure what cases it to happen.

**Comment by Gameslinx** [comment]
Not caused by parallax, which doesn't affect craft physics at all
