### ISSUE TITLE
corrupted download 

### ISSUE THREAD

**Issue by mason77712** [Gameslinx/Tessellation#68]
using winwar error message: 
! C:\Users\mason\Downloads\Tessellation-master (1).zip: Unexpected end of archive
! C:\Users\mason\Downloads\Tessellation-master (1).zip: The archive is corrupt

**Comment by Faladoru** [comment]
Same here. I've downloaded 2 different versions, both corrupted.

**Comment by Gameslinx** [comment]
Hi, don't use winrar to open this. Use Windows Explorer or 7zip to open it. It isn't a rar archive.
