### ISSUE TITLE
Shaddow flickering

### ISSUE THREAD

**Issue by Di0so** [Gameslinx/Tessellation#69]
Why does the terrain on kerbin have black shadow flickering 
i really love this mod how do I fix it :( 
note: I don't have any visual mod other than scatterer

**Comment by Di0so** [comment]
![image](https://user-images.githubusercontent.com/89231035/130167574-cdb5a9c6-5e71-43bb-b510-bb76613d64e4.png)

**Comment by Gameslinx** [comment]
Enable depth buffer mode in scatterer settings.
