### ISSUE TITLE
I really have no idea what title to use its 4am...

### ISSUE THREAD

**Issue by Apobu** [Gameslinx/Tessellation#7]
Hi, firstly I want to point out how great your work is, I very much admire the effort you've put in this project, so thumbs up to that! 
However I've been having trouble downloading your mod in my ksp.. I'm currently running MacOS and have followed the instructions very carefully. when I load up the game it crushes right before it loads the save. If I delete the Kopernicus files it actually loads the game but not the mod. So im really confused and I can't find the root of the issue. Also I have ksp 1.10.1 and don't have any other mods installed (probably should have started this with those details)
Anyway, you are amazing, idk if im getting an answer or not but your work is fantastic!! keep creating mods, sometimes🙃❤️

**Comment by Gameslinx** [comment]
Mac support is currently very limited. I'm working on it, but right now it doesn't work for MacOSX

**Comment by Apobu** [comment]
> Mac support is currently very limited. I'm working on it, but right now it doesn't work for MacOSX

that's ok, either way, big fan of yours thank you for your feedback :)
