### ISSUE TITLE
CKAN says Parallex is good for 1.12.9, but getting message saying not supported

### ISSUE THREAD

**Issue by linuxgurugamer** [Gameslinx/Tessellation#71]
KSP 1.12.2, using Parallax 1.3.0, on Windows 10
CKAN shows that it's good up to 1.12.9

When I started KSP, I get the following message both on screen and in the log file:

[Parallax] DidntReadInstallationInstructionsException: Parallax is not supported on this version of KSP. 

There is no .version file, so I am unable to verify anything else about this.
Log file attached in zip

[Parallax.zip](https://github.com/Gameslinx/Tessellation/files/7112455/Parallax.zip)

**Comment by Gameslinx** [comment]
Error in my part by not updating the version in the dll that checks it. Fixed in 2.0.0
