### ISSUE TITLE
Cloud Shadow Artifacts

### ISSUE THREAD

**Issue by eipiguy** [Gameslinx/Tessellation#72]
Hey friends,
I just got a new RTX 3080, so I decided to install all the standard visual mods: EVE, scatterer, DistantObject, Parallax, AstronomersVisualPack, and TUFX. They are all at their latest versions as of 28Sep2021

I'm getting weird surface artifacts from cloud shadows:
![Screenshot (2)](https://user-images.githubusercontent.com/12653044/135187707-eef1472a-c27e-4f69-824e-fc81c5a3825f.png)

![Screenshot (6)_LI](https://user-images.githubusercontent.com/12653044/135187845-a7f2a51c-e816-4beb-bc27-d9b2cbf41fec.jpg)

It's much more apparent when on the ground, but there are other issues with similar pictures, and I'd have to wait for a cloud to pass overhead to end up with the same thing anyway, so I'll just link them:
https://github.com/Gameslinx/Tessellation/issues/60
https://github.com/Gameslinx/Tessellation/issues/63

I've seen the above issues solved by changing the scatterer option "useDepthBufferMode=true", but my setup is already configured that way. This is the only plugin with issues matching the above screenshots, so I'm assuming it's something related.

I've attached my log and my scatterer config(as a txt file).
[KSP.log](https://github.com/Gameslinx/Tessellation/files/7248211/KSP.log)
[config.txt](https://github.com/Gameslinx/Tessellation/files/7248219/config.txt)

Thank you for your help,
Neal

**Comment by Gameslinx** [comment]
Thank you. I am going to attempt to fix this in the next update

**Comment by Scioss** [comment]
I have the same artifacts with cloud's shadow

**Comment by Scioss** [comment]
Same for me, I tried everything but nothing work
