### ISSUE TITLE
Random holes appearing with and without ground tesselation.

### ISSUE THREAD

**Issue by CanadianMaps** [Gameslinx/Tessellation#76]
![image](https://user-images.githubusercontent.com/38082663/155131934-1802836f-9a5a-4367-9349-0cb5ee1ddfcd.png)
Random holes are appearing on every single body (here pictured Mün), regardless of whether or not tessellation is on. They appear on Parallax 1.3.0 and 1.3.1

**Comment by Gameslinx** [comment]
Fixed as of 2.0.0
