### ISSUE TITLE
How do I install Parallax on 1.12x

### ISSUE THREAD

**Issue by Razedt38** [Gameslinx/Tessellation#78]
The installation instructions kind of confused me. I was wondering if I should use KopernicusBE or regular Kopernicus for 1.12 and above?

**Comment by Apobu** [comment]
You can just use kopernicus. In the main paralax page right below the github link it says "Make sure you install Kopernicus from R-T-B."

heres a link to the latest kopernicus-----https://github.com/kopernicus/kopernicus/releases 
<3
