### ISSUE TITLE
Unable to open archive file ... Wireframe-macosx.unity3d

### ISSUE THREAD

**Issue by scolebrook** [Gameslinx/Tessellation#79]
I see this in the logs on launch:
[ERR 17:53:00.208] Unable to open archive file: /Users/me/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/KSP.app/Contents/../../GameData/Parallax/Shaders/Wireframe-macosx.unity3d

[ERR 17:53:00.208] Failed to read data for the AssetBundle 'Wireframe-macosx.unity3d'.

[LOG 17:53:00.208] Failed to load bundle at
[LOG 17:53:00.208] Path: /Users/me/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/KSP.app/Contents/../../GameData/Parallax/Shaders/Wireframe-macosx.unity3d

Running version 1.3.1. M1 Pro processor, OS 12.3. Could the fact I'm not on an Intel mac be related given the graphics system changes?

**Comment by Gameslinx** [comment]
This was an error in my release. I would use Wireframe for debugging and it is not crucial to the mod itself - just debris I forgot to remove. You can safely ignore this
