### ISSUE TITLE
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.

### ISSUE THREAD

**Issue by FrostBird347** [Gameslinx/Tessellation#8]
Although the game loads and shows the main menu, kopernicus shows a warning stating that some planets could not be loaded.
Saves can not be opened or created as it never finishes loading.

[KSP.log](https://github.com/Gameslinx/Tessellation/files/5541958/KSP.log)

**Comment by Gameslinx** [comment]
Please submit your full log. Sounds like you don't have Parallax Core installed

**Comment by Gameslinx** [comment]
This is due to you being on MacOSX. I'm looking into why the shader is not supported, but it'll take time because I don't have anything to test it on

**Comment by Gameslinx** [comment]
Small update - It may be due to the shader using non-square matrices. OpenGL ES doesn't support this, but OpenGL does. I'll keep you updated in case those changes work

**Comment by Gameslinx** [comment]
Fixed, next update will include a build for MacOSX and Linux
