### ISSUE TITLE
Nor vessels or kerbals touch the ground on any planet

### ISSUE THREAD

**Issue by Apobu** [Gameslinx/Tessellation#80]
I know things have changed in the last couple releases but kerbals/crafts don't seem to like the ground very much. In some cases, mainly on mountains/hills, the either float or go under the ground. I use paralax 13.1 on ksp 12.2 with stock textures, stock planets and kopernicus release-90. 

here's a list of other mods i have but i dont think they interfere:

AstronomersVisualPack, B9PartSwitch, CommunityCategoryKit, DistantObject, EnvironmentalVisualEnhancements, KAS, KerbalEngineer, KerbalReusabilityExpansion, Kopernicus, MechJeb2, ModularFlightIntegrator, NavyFish, NearFutureProps, Parallax, Parallax_StockTextures, PlanetShine, ReStock, ReStockPlus, Scatterer, ScattererAtmosphereCache, Sigma, SoundsOfSpace, Squad, SquadExpansion, StationPartsExpansion, StationPartsExpansionRedux, StockWaterfallEffects, Waterfall, ModuleManager.4.2.

[KSP.log](https://github.com/Gameslinx/Tessellation/files/8620181/KSP.log)

i know you can see the mods i have from the log but... idk haha

update:
i just noticed, when i run the game i get a message saying "parallax not running on a supported version of ksp" even tho i am sure i have parallax 13.1 and ksp 1.12.2, however no other warning. (oh and city lights flickering but thats a known issue just mentioning it)

**Comment by Gameslinx** [comment]
Fixed in 2.0.0
