### ISSUE TITLE
Terrain scatters looking flat & terrible performance on the Mun

### ISSUE THREAD

**Issue by Scrashdown** [Gameslinx/Tessellation#81]
Hi, I am getting two problems at the same time:

1. Duna, Gilly and to some extent the Mun's surfaces look quite flat. Is it supposed to look like that?
![20220730170902_1](https://user-images.githubusercontent.com/14946298/181923459-1977c9ad-5fd4-469a-90fc-9b5e3ba8abd9.jpg)
![20220730170943_1](https://user-images.githubusercontent.com/14946298/181923461-babbad99-b47d-45b9-9883-7036c8f27692.jpg)
![20220730171012_1](https://user-images.githubusercontent.com/14946298/181923463-b5f97d80-78ec-47fb-aca4-ff24f3a6bbad.jpg)

2. On the Mun, I am getting about 9 FPS. Here are my system specs:

CPU: AMD Ryzen 3900 X
RAM: 32 GB
GPU: AMD RX 5700 XT
OS: EndeavourOS (Linux)
`uname -a`: `Linux PIMBLOKTO 5.18.14-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Jul 2022 11:46:17 +0000 x86_64 GNU/Linux`

[KSP.log](https://github.com/Gameslinx/Tessellation/files/9226764/KSP.log)

Let me know if more info is needed.

**Comment by Gameslinx** [comment]
Fixed as of 2.0.0
