### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 3Dprinted1** [Gameslinx/Tessellation#84]
I tried everything and i even did a fully stock save but still i don't see any grass or rocks on the moon.
[KSP.log](https://github.com/Gameslinx/Tessellation/files/9492311/KSP.log)
![20220905174543_1](https://user-images.githubusercontent.com/88336131/188520688-cb6bce8a-cea2-4612-a1d7-31d3ac88b8ce.jpg)

**Comment by lostadventur** [comment]
I have the same problem, clean install of the mods and have no grasses and such

**Comment by lostadventur** [comment]
Update: If you just create a vessel it spawns, at least for me. I'm sure it will be fix in the future where you can see it without being actually in game in a craft.

**Comment by HerrCraziDev** [comment]
Even in game in a vessel, I see absolutely nothing but the vanilla terrain. Running latest KSP with Kopernicus and Parralax.

**Comment by Starfire70** [comment]
Hey all. I had this same issue.
Turned out that the stock textures download was not complete, it was missing about 300MB.
The file sizes should be:
Parallax-2.0.0.zip 4086 KB
Parallax_StockTextures-2.0.0.zip 1,860,104 KB
Parallax_ScatterTextures-2.0.0.zip 1,151,576 KB
Also you won't see scatter around the KSC, you'll need to head west into the grassland and you'll see the new scatter.

**Comment by DennisKerman** [comment]
I had a **mod-conflict** with an old EVE-pack. I removed it and got Spectra instead.
Working fine now!

**Comment by lolife02** [comment]
![Unbenannt](https://user-images.githubusercontent.com/95658367/189521518-2a4d322a-678c-4d6c-a197-c9debd741086.PNG)
Same problem here, no signs of the mod doing anything other than the settings notification on startup. I only use a few pretty common mods, any chance there's an incompatibility?

**Comment by Gameslinx** [comment]
There was an issue on CKAN and Github in the first few hours of the release which caused this.
Reinstalling now should work fine, and there are also installation instructions on the forum OP with a video.

**Comment by lolife02** [comment]
I only downloaded the mod a few days ago and tried various reinstalls since then, sadly without success. It's still occuring for me.
