### ISSUE TITLE
Ike missing scatters everything else works everywhere else

### ISSUE THREAD

**Issue by RowRows** [Gameslinx/Tessellation#86]
Kerbin duna mun minmus etc are all working fine except for Ike where the scatters are missing even though the textures and configs exist in the game data folder for Ike. Tried it on a fresh save as well but same result.
![KSP_x64_lA38F7emVL](https://user-images.githubusercontent.com/112999794/188781733-fe3d1c5f-7da8-4a66-9e8f-1e14db341ee9.jpg)
[KSP.log](https://github.com/Gameslinx/Tessellation/files/9502456/KSP.log)

**Comment by Gameslinx** [comment]
Set your terrain quality to high. Ike has scatters.

**Comment by RowRows** [comment]
scatters, terrain, textures are turned all the way up. I cheated the same craft into different places on Ike and I have different crafts even on different bodies, Eve, minmus, Duna, mun, kerbin, eeloo, moho, jool system and they all have scatters except Ike, not sure where the problem lies or if it can be fixed I just wanted to document this here for future ref.

**Comment by Gameslinx** [comment]
Ike should have scatters everywhere. Check to see if the config for Ike exists (Parallax_StockTextures/_Scatters/Configs/Ike). Try deleting Settings.cfg and let KSP regenerate it, then set your settings again and restart the game. Debris from old planet mods or old mods could be adjusting the terrain quality without you knowing

**Comment by RowRows** [comment]
![KSP_x64_4OfR0ZCVI6](https://user-images.githubusercontent.com/112999794/189537235-0a240fda-87ff-4bf4-9bf4-332e63d1de02.jpg)
![KSP_x64_2GPxQypJNL](https://user-images.githubusercontent.com/1129
![KSP_x64_KR4RY3uf53](https://user-images.githubusercontent.com/112999794/189537273-132dcf73-cb6d-41a7-8eec-8f5086c9418d.jpg)
99794/189537241-ddbf64c6-4f06-4f81-82e1-03dd2eefa402.jpg)
![KSP_x64_5DQ2wt25Da](https://user-images.githubusercontent.com/112999794/189537265-afb6030e-d771-4b5c-a831-3e31835acb5a.jpg)

![ApplicationFrameHost_8tFZ0oaWlu](https://user-images.githubusercontent.com/112999794/189537245-2ac22626-7012-448b-8e8e-c891e58d1e65.jpg)

![KSP_x64_Xq5nEwFmXG](https://user-images.githubusercontent.com/112999794/189537317-3af9cb1b-55f4-49b6-9c21-5c1038f16d84.jpg)

and then Ike on the other hand 
![KSP_x64_FsvT3HPWBy](https://user-images.githubusercontent.com/112999794/189537286-925c804c-6916-476b-ad82-88a24d9e71ec.jpg)
![KSP_x64_uax2AJDkzt](https://user-images.githubusercontent.com/112999794/189537299-0eba8d7b-ab93-4571-ad99-7a68a79e1a42.jpg)

**Comment by RowRows** [comment]
> Ike should have scatters everywhere. Check to see if the config for Ike exists (Parallax_StockTextures/_Scatters/Configs/Ike). Try deleting Settings.cfg and let KSP regenerate it, then set your settings again and restart the game. Debris from old planet mods or old mods could be adjusting the terrain quality without you knowing

Ill try this thanks. Appreciate you.

**Comment by RowRows** [comment]
Deleting the settings.cfg didnt work either, tried a whole new install with completely stock build and just parallax and dependencies and same issue on Ike. I have the ike cfg and the textures just doesnt load for whatever reason. the stock new install had redownloaded parallax files just incase some data got corrupted in the first download but still nothing.
