### ISSUE TITLE
Terrible performance on the Mun, and maybe Duna (but looks like in the trailer)

### ISSUE THREAD

**Issue by Scrashdown** [Gameslinx/Tessellation#89]
Hi, first of all, congratulations for the amazing work! This mod looks mind-boggingly good.

Sadly, I am getting terrible performance on the Mun, with around 3-5 FPS. On Duna, I am getting about 35 FPS.

I think the scatters render correctly though, to me this looks like what is shown in the trailer:

![20220908011003_1](https://user-images.githubusercontent.com/14946298/188999093-b23f0486-09bf-46b6-9319-9f33c2c3892e.jpg)

My specs:

CPU: AMD Ryzen 9 3900 X
GPU: AMD RX 5700 XT
RAM: 32 GB

OS: Linux, but running via Proton 7.0-4 to get DirectX
DE: KDE Plasma Wayland

Resolution: 2560x1440

Running Parallax with default settings. No other mod besides Kopernicus.

[KSP.log](https://github.com/Gameslinx/Tessellation/files/9522109/KSP.log)

Let me know if you need more info.

**Comment by Xenunxenunowski** [comment]
Probably due to shader compilation + the fact that you had to use proton which adds quite a lot of overhead

**Comment by muhzn1991** [comment]
Got almos the same , but also on Kerbin, but ONLY when firing the engines close to the ground (or when landing and close to the ground), after engine Shutdown , everything is normal.

CPU: i9-9900K
GPU: RTX 3080
RAM: 32GB

OS: Windows

Resolution 2560x1440

Modlist:
![image](https://user-images.githubusercontent.com/76413452/189419665-d03abf13-29bf-4493-81c1-45bbef8a9985.png)


I have in mind, that the thing is the Waterfall Mod in connection with parallax, i will try when I'm at home

**Comment by muhzn1991** [comment]
Yeah , after deleting Waterfall mod, it works. (one for your incompatibility list )

**Comment by Gameslinx** [comment]
If you have anti-aliasing set to 8x, you will get terrible performance. It has been bugged in stock KSP for years, and people are only finding out about it now that scenes are more complex.
Turn it off, use Scatterer's or TUFX's, and let me know if that solves your issue

**Comment by Scrashdown** [comment]
Thanks, disabling AA alone didn't help, but I was able to get about 40 FPS with no AA, pixel light count = 4, and reflection refresh mode = OFF. After fiddling with the settings, it looks like these 3 parameters seem to impact FPS greatly on my machine.

I also noticed turning off all lights on my ship helped greatly. With the above setting, I went from 40 FPS to 68 FPS. Hope that helps. For reference, the scene I am using to do these tests is the "Mun Rover" scenario.

**Comment by Scrashdown** [comment]
> Lights are horribly inefficient in KSP. Relevant topic: Forward VS Deferred rendering path. Sadly, it's something we will all have to deal with. Nothing I can do on my end - just a symptom of an 11 year old game

No problem, thanks for the info.
