### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by BlockListed** [Gameslinx/Tessellation#9]
I download Parallax, Parallax stock textures, Kopernicus(R-T-B), Kerbal Engineer Redux, Kerbal reusability expansion and trajectories and put everything in my gamedata folder, but on game startup it says:
fparallax is missing dependancy kopernicus
parallax is missing dependancy Parallax stock
parallax is missing dependancy Parallax (core)

after that in my save the game lags (2-5 fps) and the debug console spams nullreference errors.

OS: Pop OS 20.10
Driver: NVIDIA proprietary 455
Game: KSP 1.10.1 Breaking ground and Making history

**Comment by merlinschumacher** [comment]
I have the same issues.

**Comment by Gameslinx** [comment]
Can you both try this? It worked for another user. 

Step 1: Enable steam play by going into settings and enable it for all titles. (Thus not native.)
Step 2: Restart steam. (Pop up)
Step 3:Right click on Ksp. 
Step 4: go to properties.
Step 5:click "Force the use if a specific Steam play Combatability tool".
Step 6:(This varies from distrobution to distrobution. Tis for Pop_oS 20.19) click on the drop down and then select proton 5.13-2.

**Comment by merlinschumacher** [comment]
I've tried it, but get the same messages.

**Comment by Gertinin** [comment]
Hey I'm the person that wrote guide,Since (at least from what I can tell) You use arch, so try different compatability tools, plus I was on the 1.1.1b instead of 1.1.1.

**Comment by Gameslinx** [comment]
Fixed, added support for OpenGL for MacOSX and Linux
