### ISSUE TITLE
Terrain outside of VAB is completely black

### ISSUE THREAD

**Issue by NotSerum** [Gameslinx/Tessellation#90]
I followed the download instructions and downloading the right versions, at least I think, yet the terrain textures are just missing/broken
![image](https://user-images.githubusercontent.com/69740790/189033458-9b45606f-4d28-458d-bcd4-1629a7f402bd.png)

Specs: 
GPU: i7 10700k
GPU: 3060TI
RAM: 16 Gb
Running on Windows 10 with several mods that I can provide if needed

**Comment by muhzn1991** [comment]
It seems, that also stock parts appear much darker after installing the mod

**Comment by Gameslinx** [comment]
You can open 'IncreaseSubdivisionCount.cfg' and remove the line that sets the ambient light to 0. Will be removed in an update

**Comment by NotSerum** [comment]
> You can open 'IncreaseSubdivisionCount.cfg' and remove the line that sets the ambient light to 0. Will be removed in an update

I deleted the segment with ambient light color because it was the only line mentioning ambient light, but it didnt do anything 
![image](https://user-images.githubusercontent.com/69740790/189567419-d0e83ef7-c747-4b92-9fee-cde5db203659.png)

**Comment by MaggiWuerze** [comment]
I have the same issue, removing the line from the cfg file did not help.
