### ISSUE TITLE
Pitch black Space Center veiw during night, no ambeint light. 

### ISSUE THREAD

**Issue by douglasdtlltd** [Gameslinx/Tessellation#91]
Is there supposed to be ambient light in space center view?

Space Center veiw is pitch black in during night time with only this mod installed. 
![pic2](https://user-images.githubusercontent.com/25917193/189069713-a0d7dda9-2059-4687-9fa3-5b0a77b70c85.png)
![pic3](https://user-images.githubusercontent.com/25917193/189069731-c1f90f86-ce65-4126-a286-b4a9e41d55dd.png)
[KSP_log.zip](https://github.com/Gameslinx/Tessellation/files/9524983/KSP_log.zip)

Last image is with my mods without Parallax installed. 
![image](https://user-images.githubusercontent.com/25917193/189070276-3cd2240f-16de-43b2-b61a-2a65921f2b27.png)
![pic1](https://user-images.githubusercontent.com/25917193/189070309-5235cb2b-57b6-4947-9f8b-e60106d2808a.png)

**Comment by paxon57** [comment]
From my experience PlanetShine doesn't like Parallax, try getting rid of it.

**Comment by Gameslinx** [comment]
Will be fixing this in the next textures update. For now, you can edit the config file 'IncreaseSubdivisionCount.cfg' and remove the line that sets the ambient light to 0
