### ISSUE TITLE
No clouds on Kerbin, Duna, Laythe, ...

### ISSUE THREAD

**Issue by Folkoer** [Gameslinx/Tessellation#93]
Everything seems to work normally besides clouds. Kerbin, Duna and Laythe don't have any clouds atm.
My logs:
https://www.dropbox.com/s/ifk4kxjvrhno7iv/KSP.log?dl=0

https://www.dropbox.com/s/kx2toz83ofzm44q/Player.log?dl=0

**Comment by RowRows** [comment]
Clouds are part of a different mod, not parallax. You need environmental visual enhancements with a config file to go along with it.

**Comment by Folkoer** [comment]
I do have EVE and scatterer installed as well, forgot to mention

**Comment by RowRows** [comment]
EVE needs a config that does not come with parallax. try spectra, avp or something similar.

**Comment by Gameslinx** [comment]
Non-Parallax related issue.
