### ISSUE TITLE
Game does not work (dont know how to install)

### ISSUE THREAD

**Issue by Terrabey** [Gameslinx/Tessellation#94]
Hello Parallax Team,
I need help by installing Parallax because it does not work an there are no issues shown as well that I am pretty confused with the Guide on the Mod when Installed in the Folder. Kopernicus is already installed I just dont know which Parallax, Parallax_scatter and Parallax Stock Folder need äs to be pit in the GameData Folder.

**Comment by StarSmasher44** [comment]
All 3 folders must be put into GameData, that is parallax, parallax_scatter AND the stocktextures folder.

Plus you need Kopernicus, but you already managed that one :)

**Comment by Gameslinx** [comment]
Updated installation instructions on the OP with a video.
