### ISSUE TITLE
Crash on loadings and SOI change

### ISSUE THREAD

**Issue by paxon57** [Gameslinx/Tessellation#96]
It doesn't happen always, I would say 30% chance that it will crash during these events.

RAM, VRAM and GPU usage all skyrocket to 100% causing other apps on my PC to crash and both screens to go dark for few sec.

My rig: 
RTX 2070 Super
Ryzen 9 5900X
16 GB DDR4 3200Mhz RAM

KSP settings are set on highest (achieving smooth gameplay) with Anti Aliasing disabled

**Comment by Gameslinx** [comment]
Thanks for the report. This is likely a memory related error and will happen with more mods installed.
That being said, I am working on reducing the memory usage. I have succeeded in a 30% reduction so far, and I am hoping to get it down lower. This should stop your crashes when I release the update

**Comment by paxon57** [comment]
Ok, thank you for your work, you created an amazing mod in here!

**Comment by Gameslinx** [comment]
Check the latest release. There is a ~40% memory reduction on what Parallax normally uses
