### ISSUE TITLE
I can't install Parallax in my KSP

### ISSUE THREAD

**Issue by laquax** [Gameslinx/Tessellation#99]
Although I do everything right, the mode does not load, I set my settings to the desired level, I set up the required copernicus mode, and it appears to be installed on the loading screen, but what I see when I enter is just default ksp. And I did the update. Please help.

![Screenshot_1](https://user-images.githubusercontent.com/113732197/190826630-c1b2a288-d52e-4b74-a80d-4660a2fd2bb0.png)
![Screenshot_2](https://user-images.githubusercontent.com/113732197/190826633-c3614a33-f005-4472-910f-e9f3a515ec6f.png)
![Screenshot_3](https://user-images.githubusercontent.com/113732197/190826637-3db47e53-b037-4d5c-b5a3-98390c88b4c6.png)
![Screenshot_4](https://user-images.githubusercontent.com/113732197/190826638-e5cf23b5-5a9a-462c-8cba-24c8f34fd240.png)

**Comment by Gameslinx** [comment]
Have you actually gone and launched a craft on the launch pad / runway?

**Comment by staker446** [comment]
I have the same issue, i tried to uninstall the game, reinstall the zips, install the latest version of the mod ans still not working
![no funca](https://user-images.githubusercontent.com/113990547/191248928-bcfae671-ef9f-4ab3-8348-9847c94a985c.PNG)
![20220920133552_1](https://user-images.githubusercontent.com/113990547/191249291-54ab43e4-31c0-4874-8b08-e6b38b6ea044.jpg)
![20220920133619_1](https://user-images.githubusercontent.com/113990547/191249305-217a9e6c-f8c7-4689-8ee7-3663bfde21cc.jpg)

**Comment by Gameslinx** [comment]
Parallax does not change anything in the map view. It is ground terrain only. Go into the flight view and try to launch a craft. It looks installed correctly

**Comment by Gameslinx** [comment]
Hi, Parallax does not add clouds. That is the works of Environmental Visual Enhancements.
Scatterer makes the atmosphere look better, EVE makes the clouds appear, and Parallax makes the ground look better.
I would recommend installing a visual pack, such as Astronomer's Visual Pack (AVP) which combines Scatterer and EVE. It is compatible with Parallax. I think this is what you are looking for

**Comment by staker446** [comment]
Ok thanks, I didn't understand the mod well because I'm not very good at English.
I will install what you say.
Thank you very much!!!
